const GAME_DATA = {
  orgUnits: [
    {
      id: "ceo",
      name: "公司頂層",
      tagline: "董事長、執行長、最高層決策與跨群取捨",
      capability: ["決策授權", "資源取捨", "跨群優先級"],
      risk: "離現場太遠時，會把複雜問題壓成口號。",
      verification: "已對齊：董事會層級、執行長以下決策架構。",
      counters: ["authority", "tradeoff", "scope"],
      links: ["sales-marketing", "tech-rd", "newbiz", "general-mgmt"]
    },
    {
      id: "consulting",
      name: "顧問室本部",
      tagline: "資深顧問、制度記憶與高階輔助判斷",
      capability: ["制度記憶", "高階諮詢", "風險提醒"],
      risk: "若沒有接到一線問題，容易停留在原則層。",
      verification: "已對齊：顧問室本部。",
      counters: ["memory", "advice", "review"],
      links: ["ceo", "general-mgmt"]
    },
    {
      id: "general-mgmt",
      name: "總管理處",
      tagline: "公司級管理節奏、AI 種子計畫與跨群推動",
      capability: ["管理節奏", "變革推動", "跨群協調"],
      risk: "變革如果只停在倡議，會缺少落地隊形。",
      verification: "已對齊：總管理處 HR/IR/策經/稽核法務/永續。",
      counters: ["change", "seed", "cadence"],
      links: ["ceo", "ops-mgmt", "tech-rd", "newbiz"]
    },
    {
      id: "sales-marketing",
      name: "業務行銷群",
      tagline: "業務一至七處、行銷發展處、品牌與客戶訊號",
      capability: ["客戶情境", "品牌需求", "商業化路徑"],
      risk: "客戶語言若沒有翻成產品規格，會在交接時失真。",
      verification: "2026/05 PDF 對齊：業務一/二/三/五/六/七處、行銷發展處、Marketing Team。",
      counters: ["brand", "client", "market"],
      links: ["ceo", "newbiz", "tech-rd"]
    },
    {
      id: "ops-mgmt",
      name: "營運管理群",
      tagline: "資訊、財會、平台治理與營運支撐",
      capability: ["系統治理", "財務約束", "資料基礎"],
      risk: "若太晚進場，產品會先長出不可維護的流程。",
      verification: "較早期累積版本，尚未經 2026/05 組織圖驗證：資訊處、財會管理處。",
      counters: ["system", "finance", "governance"],
      links: ["general-mgmt", "newbiz", "tech-rd"]
    },
    {
      id: "tech-rd",
      name: "工務研發群",
      tagline: "開發暨技術處、工務處、運籌處；3D研發中心隸屬開發暨技術處",
      capability: ["研發落地", "3D 標準", "品質閘門"],
      risk: "需求邊界不清時，會用高執行力做出錯方向；知識鎖倉會形成單點風險。",
      verification: "2026/05 PDF 對齊：開發暨技術處、3D研發中心、工務處；運籌處仍為較早期累積版本，尚未經 2026/05 組織圖驗證。",
      counters: ["rd", "3d", "gate"],
      links: ["newbiz", "sales-marketing", "ops-mgmt"]
    },
    {
      id: "overseas",
      name: "海外產區",
      tagline: "GLR/GLS、越南與跨產區製造現場",
      capability: ["產區落地", "製造限制", "跨地回饋"],
      risk: "若只用台北視角看現場，會誤判地理成本與執行限制。",
      verification: "較早期累積版本，尚未經 2026/05 組織圖驗證：海外產區 10 個地區。",
      counters: ["factory", "region", "feedback"],
      links: ["tech-rd", "sales-marketing"]
    },
    {
      id: "newbiz",
      name: "新事業發展群",
      tagline: "數位產品發展中心、智慧紡織發展中心",
      capability: ["產品實驗", "GTM", "AI prototype"],
      risk: "沒有真實 demo 與回饋迴路時，聲量無法轉成採用。",
      verification: "2026/05 PDF 對齊：數位產品發展中心、智慧紡織發展中心。",
      counters: ["product", "ai", "feedback"],
      links: ["ceo", "tech-rd", "sales-marketing", "ops-mgmt"]
    },
    {
      id: "investment",
      name: "轉投資企業",
      tagline: "轉投資角色與外部事業連結",
      capability: ["外部資源", "事業連動", "策略彈性"],
      risk: "若和主組織任務沒有清楚接口，容易只剩名義連線。",
      verification: "較早期累積版本，尚未經 2026/05 組織圖驗證。",
      counters: ["venture", "external", "link"],
      links: ["ceo"]
    },
    {
      id: "pending",
      name: "Makalot / 待定位",
      tagline: "人名先掛上，組織歸屬待 makalot-org 校正",
      capability: ["待補"],
      risk: "不能用單場會議情境推定正式部門。",
      counters: ["unknown"],
      links: ["ceo", "sales-marketing", "tech-rd", "newbiz"]
    }
  ],
  orgDirectory: [
    { id: "board", unit: "ceo", name: "董事會", members: [] },
    { id: "audit-office", unit: "ceo", name: "稽核室", members: [] },
    { id: "ceo-office", unit: "ceo", name: "執行長 / 公司頂層", members: ["alex"] },
    { id: "decision-integration-committee", unit: "ceo", name: "決策整合委員會", members: [] },
    { id: "audit-committee", unit: "ceo", name: "審計委員會", members: [] },
    { id: "compensation-committee", unit: "ceo", name: "薪資報酬委員會", members: [] },
    { id: "sustainability-committee", unit: "ceo", name: "永續委員會", members: [] },
    { id: "consulting-office", unit: "consulting", name: "顧問室本部", members: ["michael-song"] },
    { id: "general-office", unit: "general-mgmt", name: "總管理處", members: ["mandy-huang"] },
    { id: "strategy-management", unit: "general-mgmt", parent: "general-office", name: "策略暨經營管理部", members: [] },
    { id: "industry-strategy", unit: "general-mgmt", parent: "strategy-management", name: "產業策略課", members: [] },
    { id: "business-management", unit: "general-mgmt", parent: "strategy-management", name: "經營管理課", members: [] },
    { id: "human-resources", unit: "general-mgmt", parent: "general-office", name: "人力資源部", members: [] },
    { id: "compensation-management", unit: "general-mgmt", parent: "human-resources", name: "薪酬管理課", members: [] },
    { id: "talent-development", unit: "general-mgmt", parent: "human-resources", name: "人才發展課", members: [] },
    { id: "general-affairs", unit: "general-mgmt", parent: "human-resources", name: "總務管理課", members: [] },
    { id: "hrbp", unit: "general-mgmt", parent: "human-resources", name: "河內子公司 HR", members: [] },
    { id: "recruiting", unit: "general-mgmt", parent: "human-resources", name: "招募暨任用課", members: [] },
    { id: "sustainability-development", unit: "general-mgmt", parent: "general-office", name: "永續發展部", members: [] },
    { id: "investor-relations", unit: "general-mgmt", parent: "general-office", name: "投資人關係組", members: [] },
    { id: "audit-legal", unit: "general-mgmt", parent: "general-office", name: "稽核暨法務組", members: [] },
    { id: "sales-group", unit: "sales-marketing", name: "業務行銷群", members: ["tiffany-sung"] },
    { id: "sales-1", unit: "sales-marketing", name: "業務一處", members: ["karen-chou", "ivy-liao", "erica-hsu", "ellen-chang"] },
    { id: "sales-2", unit: "sales-marketing", name: "業務二處", members: ["tania-liu", "jessica-wang", "vince-hsu", "erica-chang"] },
    { id: "sales-3", unit: "sales-marketing", name: "業務三處", members: ["cynthia-fu"] },
    { id: "sales-5", unit: "sales-marketing", name: "業務五處", members: ["sasha-lai", "ruo-chen", "maggie-tsai"] },
    { id: "sales-6", unit: "sales-marketing", name: "業務六處", members: ["arthur-kuo"] },
    { id: "sales-7", unit: "sales-marketing", name: "業務七處", members: ["mandy-chen", "emily-chak", "melody-lin", "hazel-lin", "maggie-chen"] },
    { id: "marketing-dev", unit: "sales-marketing", name: "行銷發展處", members: ["douglas-lu", "yulia-huang"] },
    { id: "finance-admin-office", unit: "ops-mgmt", name: "財會管理處", members: ["christine-wen"] },
    { id: "accounting-1", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計一部", members: [] },
    { id: "accounting-2", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計二部", members: [] },
    { id: "accounting-3", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計三部", members: [] },
    { id: "finance-dept", unit: "ops-mgmt", parent: "finance-admin-office", name: "財務部", members: [] },
    { id: "stock-affairs-project", unit: "ops-mgmt", parent: "finance-admin-office", name: "股務暨專案組", members: [] },
    { id: "risk-investment-project", unit: "ops-mgmt", parent: "finance-admin-office", name: "風控/投資評估專案小組", members: [] },
    { id: "overseas-finance-investment", unit: "ops-mgmt", parent: "finance-admin-office", name: "海外財會組織/轉投資", members: [] },
    { id: "it-office", unit: "ops-mgmt", name: "資訊處", members: ["benjamin-hsieh"] },
    { id: "app-development", unit: "ops-mgmt", parent: "it-office", name: "應用開發部", members: [] },
    { id: "app-modernization-engineering", unit: "ops-mgmt", parent: "app-development", name: "現代化工程", members: [] },
    { id: "app-dev-1", unit: "ops-mgmt", parent: "app-development", name: "開發I課", members: [] },
    { id: "app-dev-2", unit: "ops-mgmt", parent: "app-development", name: "開發II課", members: [] },
    { id: "app-dev-3", unit: "ops-mgmt", parent: "app-development", name: "開發III課", members: [] },
    { id: "app-dev-4", unit: "ops-mgmt", parent: "app-development", name: "開發IV課", members: [] },
    { id: "erp-development", unit: "ops-mgmt", parent: "it-office", name: "ERP開發部", members: [] },
    { id: "erp-modernization-engineering", unit: "ops-mgmt", parent: "erp-development", name: "現代化工程", members: [] },
    { id: "system-operations", unit: "ops-mgmt", parent: "it-office", name: "系統營運部", members: [] },
    { id: "security-group", unit: "ops-mgmt", parent: "system-operations", name: "資安組", members: [] },
    { id: "system-maintenance", unit: "ops-mgmt", parent: "system-operations", name: "系統維護課", members: [] },
    { id: "digital-transformation", unit: "ops-mgmt", parent: "it-office", name: "數位轉型部", members: [] },
    { id: "dt-modernization-engineering", unit: "ops-mgmt", parent: "digital-transformation", name: "現代化工程", members: [] },
    { id: "dt-engineering", unit: "ops-mgmt", parent: "digital-transformation", name: "工程師群", members: [] },
    { id: "ai-ops-project", unit: "ops-mgmt", parent: "digital-transformation", name: "AI應用/營運與專案管理", members: [] },
    { id: "engineering-system", unit: "ops-mgmt", parent: "it-office", name: "工務系統部", members: [] },
    { id: "engineering-system-modernization", unit: "ops-mgmt", parent: "engineering-system", name: "現代化工程", members: [] },
    { id: "data-platform", unit: "ops-mgmt", parent: "it-office", name: "資料平台部", members: [] },
    { id: "software-architecture-committee", unit: "ops-mgmt", parent: "it-office", name: "軟體架構委員會", members: [] },
    { id: "api-review", unit: "ops-mgmt", parent: "software-architecture-committee", name: "API審查小組", members: [] },
    { id: "data-governance", unit: "ops-mgmt", parent: "software-architecture-committee", name: "資料治理小組", members: [] },
    { id: "dev-tech", unit: "tech-rd", name: "開發暨技術處", members: ["celia-hsu"] },
    { id: "rd-3d", unit: "tech-rd", parent: "dev-tech", name: "3D研發中心", members: ["elly", "karen"] },
    { id: "rd-3d-garment", unit: "tech-rd", parent: "rd-3d", name: "數位服飾", members: [] },
    { id: "rd-3d-garment-taipei", unit: "tech-rd", parent: "rd-3d-garment", name: "台北", members: ["adia", "yoko", "debbie", "chieh", "sixian", "jean", "rou"] },
    { id: "rd-3d-garment-chiayi", unit: "tech-rd", parent: "rd-3d-garment", name: "嘉義", members: ["yota", "jan"] },
    { id: "rd-3d-garment-pinghu", unit: "tech-rd", parent: "rd-3d-garment", name: "平湖", members: ["huihui"] },
    { id: "rd-3d-fabric", unit: "tech-rd", parent: "rd-3d", name: "數位布料", members: ["tinley", "rock"] },
    { id: "chiayi-sample-center", unit: "tech-rd", parent: "dev-tech", name: "嘉義樣品中心", members: [] },
    { id: "costing-center", unit: "tech-rd", parent: "dev-tech", name: "估碼中心", members: [] },
    { id: "technical-design", unit: "tech-rd", parent: "dev-tech", name: "技術設計部", members: ["lillian-lin"] },
    { id: "special-rd", unit: "tech-rd", parent: "dev-tech", name: "特工研發中心", members: ["artie-yu"] },
    { id: "dev-logistics-section", unit: "tech-rd", parent: "dev-tech", name: "運籌課", members: [] },
    { id: "sample-rd", unit: "tech-rd", parent: "dev-tech", name: "樣品研發部", members: ["teresa-hsueh"] },
    { id: "engineering-office", unit: "tech-rd", name: "工務處", members: [] },
    { id: "engineering-hq", unit: "tech-rd", parent: "engineering-office", name: "工務處處本部", members: ["anne-hu", "brian-lin", "evy-chen"] },
    { id: "fabric-inspection-team", unit: "tech-rd", parent: "engineering-office", name: "驗布團隊", members: [] },
    { id: "industrial-engineering", unit: "tech-rd", parent: "engineering-office", name: "工業工程部", members: [] },
    { id: "quality-management", unit: "tech-rd", parent: "engineering-office", name: "品質管理部", members: [] },
    { id: "logistics-office", unit: "tech-rd", name: "運籌處", members: [] },
    { id: "logistics-management", unit: "tech-rd", parent: "logistics-office", name: "物流管理部", members: [] },
    { id: "export-management", unit: "tech-rd", parent: "logistics-management", name: "出口管理課", members: [] },
    { id: "import-docs", unit: "tech-rd", parent: "logistics-management", name: "進口文件課", members: [] },
    { id: "production-sales-management", unit: "tech-rd", parent: "logistics-office", name: "產銷管理部", members: [] },
    { id: "digital-product", unit: "newbiz", name: "數位產品發展中心（Portal:M / StyTrix）", members: ["alex"] },
    { id: "digital-product-line-1", unit: "newbiz", parent: "digital-product", name: "Line 1 — 產品 / 3D 開發", members: ["elly", "alan", "andy"] },
    { id: "digital-product-line-2", unit: "newbiz", parent: "digital-product", name: "Line 2 — 行銷 / 專案 / 對外", members: ["vanessa", "doris", "emily", "dianne"] },
    { id: "smart-textile", unit: "newbiz", name: "智慧紡織發展中心", members: ["alex", "wayi-tsai-蔡維溢"] },
    { id: "smart-textile-line-1", unit: "newbiz", parent: "smart-textile", name: "Line 1 — Shirley Sun", members: ["shirley-sun-孫雪", "tanis-lee-李利翔"] },
    { id: "smart-textile-line-2", unit: "newbiz", parent: "smart-textile", name: "Line 2 — Evan Sheu", members: ["evan-sheu-許航碩", "jonathan-wu-鄔宗甫", "gary-yen-顏家靖", "dean-lo-羅皓文", "ian-tseng-曾奕恩"] },
    { id: "smart-textile-line-3", unit: "newbiz", parent: "smart-textile", name: "Line 3 — Jimmy Chou", members: ["jimmy-chou-周子揚", "sunny-shih-施禹安"] },
    { id: "overseas-region", unit: "overseas", name: "海外產區", members: ["annie-wang", "leo-tsai"] },
    { id: "investment-companies", unit: "investment", name: "轉投資企業", members: ["puli-yu", "hongren-huang"] },
    { id: "pending-members", unit: "pending", name: "待 makalot-org 定位", members: ["jessica", "rosa", "ruochen", "maggie", "sharon", "winnie"] }
  ],
  members: [
    {
      id: "adia",
      name: "Adia",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "10-28",
      numerology: 4,
      element: "金",
      zodiac: "天蠍座",
      archetype: "建設者",
      animal: "羊",
      star: "天相星",
      style: "重視穩定與交付，適合用清楚範圍和檢核點對齊。",
    },
    {
      id: "alan",
      name: "Alan Liu",
      localName: "劉俊毅",
      role: "資深3D技師",
      department: "數位產品發展中心 / Line 1 產品 / 3D 線",
      orgUnit: "newbiz",
      birthday: "01-31",
      numerology: 8,
      element: "水",
      zodiac: "水瓶座",
      archetype: "成就者",
      animal: "猴",
      star: "天同星",
      style: "偏好有目標、有邊界的討論，能接受新方法但需要看到產出。",
    },
    {
      id: "alex",
      name: "Alex Chou",
      localName: "周心鵬",
      role: "CEO",
      department: "公司頂層 / 執行長",
      orgUnit: "ceo",
      birthday: "05-01",
      numerology: 1,
      element: "木",
      zodiac: "金牛座",
      archetype: "領導者",
      animal: "鼠",
      star: "天府星",
      style: "適合用願景、取捨與商業結果對話，避免陷入過細的執行枝節。",
    },
    {
      id: "andy",
      name: "Andy Liu",
      localName: "柳宥良",
      role: "3D技師",
      department: "數位產品發展中心 / Line 1 產品 / 3D 線",
      orgUnit: "newbiz",
      birthday: "11-01",
      numerology: 1,
      element: "火",
      zodiac: "天蠍座",
      archetype: "領導者",
      animal: "鼠",
      star: "七殺星",
      style: "推進感強，適合給明確目標和可立即動手的切入點。",
    },
    {
      id: "chieh",
      name: "Chieh",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "03-24",
      numerology: 1,
      element: "土",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "馬",
      star: "破軍星",
      style: "能快速開局，也容易被模糊需求消耗；最好把問題變成選項。",
    },
    {
      id: "debbie",
      name: "Debbie",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "04-01",
      numerology: 1,
      element: "木",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "牛",
      star: "廉貞星",
      style: "適合直接講重點和預期成果，節奏拖太長會降低耐心。",
    },
    {
      id: "dianne",
      name: "Dianne Chen",
      localName: "陳亭妤",
      role: "行銷專員",
      department: "數位產品發展中心 / Line 2 行銷 / 專案線",
      orgUnit: "newbiz",
      birthday: "03-18",
      numerology: 7,
      element: "水",
      zodiac: "雙魚座",
      archetype: "探索者",
      animal: "雞",
      star: "太陰星",
      style: "擅長感受脈絡和受眾反應，適合先對齊語氣再進入任務。",
    },
    {
      id: "doris",
      name: "Doris Lin",
      localName: "林雅庭",
      role: "專案專員",
      department: "數位產品發展中心 / Line 2 行銷 / 專案線",
      orgUnit: "newbiz",
      birthday: "10-22",
      numerology: 11,
      element: "木",
      zodiac: "天秤座",
      archetype: "啟示者",
      animal: "豬",
      star: "天同星",
      style: "在協調和美感判斷上敏銳，適合用共識框架推進。",
    },
    {
      id: "elly",
      name: "Elly Cheng",
      localName: "程麗如",
      role: "數位產品開發總監（Line 1；兼3D研發中心）",
      department: "數位產品發展中心 / Line 1 產品 / 3D 線",
      orgUnit: "newbiz",
      birthday: "04-27",
      numerology: 7,
      element: "木",
      zodiac: "金牛座",
      archetype: "探索者",
      animal: "豬",
      star: "武曲星",
      style: "偏好結論有立場、脈絡夠完整、能回答 so what 的討論。",
    },
    {
      id: "emily",
      name: "Emily Shen",
      localName: "申書璇",
      role: "行銷專員",
      department: "數位產品發展中心 / Line 2 行銷 / 專案線",
      orgUnit: "newbiz",
      birthday: "04-29",
      numerology: 11,
      element: "木",
      zodiac: "金牛座",
      archetype: "啟示者",
      animal: "狗",
      star: "廉貞星",
      style: "重視品質與穩定判斷，適合用具體案例和明確標準溝通。",
    },
    {
      id: "jan",
      name: "Jan",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 嘉義",
      orgUnit: "tech-rd",
      birthday: "02-26",
      numerology: 8,
      element: "火",
      zodiac: "雙魚座",
      archetype: "成就者",
      animal: "鼠",
      star: "紫微星",
      style: "能把情緒感知轉成成果導向，適合先說目標再保留彈性。",
    },
    {
      id: "jean",
      name: "Jean",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "05-21",
      numerology: 3,
      element: "水",
      zodiac: "雙子座",
      archetype: "表達者",
      animal: "馬",
      star: "七殺星",
      style: "反應快、點子多，適合用短迭代和可視化產物聚焦。",
    },
    {
      id: "karen",
      name: "Karen King",
      role: "副理",
      department: "3D研發中心",
      orgUnit: "tech-rd",
      birthday: "04-22",
      numerology: 5,
      element: "火",
      zodiac: "金牛座",
      archetype: "自由者",
      animal: "虎",
      star: "七殺星",
      style: "能快速判斷現場可不可行，適合用決策選項和風險交換溝通。",
    },
    {
      id: "rock",
      name: "Rock Chu",
      role: "專員",
      department: "3D研發中心 / 數位布料",
      orgUnit: "tech-rd",
      birthday: "01-28",
      numerology: 3,
      element: "金",
      zodiac: "水瓶座",
      archetype: "表達者",
      animal: "馬",
      star: "天機星",
      style: "適合討論系統關係與替代方案，溝通時要給空間發散再收斂。",
    },
    {
      id: "rou",
      name: "ROU",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "04-04",
      numerology: 9,
      element: "火",
      zodiac: "牡羊座",
      archetype: "人道者",
      animal: "兔",
      star: "貪狼星",
      style: "對人和內容氛圍敏銳，適合給舞台、方向和清楚的成功樣貌。",
    },
    {
      id: "sixian",
      name: "Sixian",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "05-02",
      numerology: 8,
      element: "金",
      zodiac: "金牛座",
      archetype: "成就者",
      animal: "馬",
      star: "太陰星",
      style: "穩定、務實、重視成果，適合用明確 deliverable 對齊。",
    },
    {
      id: "tinley",
      name: "Tinley Wang",
      role: "專員",
      department: "3D研發中心 / 數位布料",
      orgUnit: "tech-rd",
      birthday: "10-18",
      numerology: 7,
      element: "木",
      zodiac: "天秤座",
      archetype: "探索者",
      animal: "豬",
      star: "紫微星",
      style: "適合處理探索型議題，先給脈絡和判斷準則會更穩。",
    },
    {
      id: "vanessa",
      name: "Vanessa Chou",
      localName: "周嗣萱",
      role: "行銷策略總監（Line 2）",
      department: "數位產品發展中心 / Line 2 行銷 / 專案線",
      orgUnit: "newbiz",
      birthday: "12-25",
      numerology: 5,
      element: "木",
      zodiac: "摩羯座",
      archetype: "自由者",
      animal: "鼠",
      star: "巨門星",
      style: "擅長把自由度和現實限制拉在一起，適合討論優先級與資源取捨。",
    },
    {
      id: "yoko",
      name: "Yoko",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "07-30",
      numerology: 1,
      element: "金",
      zodiac: "獅子座",
      archetype: "領導者",
      animal: "蛇",
      star: "巨門星",
      style: "適合用明確主張和成果舞台溝通，避免只給零碎任務。",
    },
    {
      id: "yota",
      name: "Yota",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 嘉義",
      orgUnit: "tech-rd",
      birthday: "04-02",
      numerology: 7,
      element: "土",
      zodiac: "牡羊座",
      archetype: "探索者",
      animal: "兔",
      star: "天府星",
      style: "適合做探索與落地之間的橋接，需要清楚問題和可試驗範圍。",
    },
    {
      id: "celia-hsu",
      name: "Celia Hsu",
      role: "處副總經理",
      department: "開發暨技術處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "開發暨技術處正式主管，3D研發中心直屬上級；適合處理研發資源、品質標準與跨部門優先級。",
    },
    {
      id: "jessica",
      name: "Jessica",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Workshop 與 GTM 情境中的內部協作角色，適合放在活動設計、受眾定位與收斂討論。",
    },
    {
      id: "rosa",
      name: "Rosa",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Workshop 情境中出現的內部角色，先作為品牌互動與內容支援卡。",
    },
    {
      id: "ruochen",
      name: "Ruo Chen",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "與 ROU / 林芓葇不同人，先作為 Workshop project 互動與需求理解角色。",
    },
    {
      id: "hazel-lin",
      name: "Hazel Lin",
      role: "A部 Development lead",
      department: "業務七處 / A部 IPS",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，適合承接市場觀察、開發素材與款式方向整理。",
    },
    {
      id: "lillian-lin",
      name: "Lillian Lin",
      role: "資深經理",
      department: "開發暨技術處 / 技術設計部",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，先作為開發 brief、樣布與款式同步角色。",
    },
    {
      id: "maggie",
      name: "Maggie",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，適合協助把客戶方向轉成素材需求與下一步行動。",
    },
    {
      id: "erica-chang",
      name: "Erica Chang",
      role: "專員",
      department: "業務二處 / A部 DKS-Calia-VRST",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，適合處理 2D 定位、版型與工差風險。",
    },
    {
      id: "sharon",
      name: "Sharon",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，先作為版型與花位交接支援卡。",
    },
    {
      id: "winnie",
      name: "Winnie",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，適合補足工廠端規格確認與量產風險視角。",
    },
    {
      id: "mandy-huang",
      name: "Mandy Huang",
      role: "群總經理",
      department: "總管理處 / 營運管理群（兼）",
      orgUnit: "general-mgmt",
      birthday: "待補",
      style: "AI 種子計畫發起者，適合啟動跨群變革、定義推動節奏與組織級授權。",
    },
    {
      id: "tiffany-sung",
      name: "Tiffany Sung",
      role: "群總經理",
      department: "業務行銷群",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務行銷群最高主管，適合把客戶訊號、品牌方向與商業取捨拉回決策桌。",
    },
    {
      id: "anne-hu",
      name: "Anne Hu",
      role: "處長",
      department: "工務處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "工務處主管，負責品質、工業工程與大貨技師團隊的現場落地判斷。",
    },
    {
      id: "benjamin-hsieh",
      name: "Benjamin Hsieh",
      role: "處長",
      department: "資訊處",
      orgUnit: "ops-mgmt",
      birthday: "待補",
      style: "資訊處主管，適合處理系統、權限、資料治理與 AI 工具落地支援。",
    },
    {
      id: "christine-wen",
      name: "Christine Wen",
      role: "處副總經理",
      department: "財會管理處",
      orgUnit: "ops-mgmt",
      birthday: "待補",
      style: "財會管理處主管，適合在新產品、展會與投資議題中補上成本、預算與風險約束。",
    },
    {
      id: "wayi-tsai",
      name: "Wayi Tsai",
      role: "資深經理",
      department: "智慧紡織發展中心",
      orgUnit: "newbiz",
      birthday: "待補",
      style: "智慧紡織發展中心 lead，適合把專案線、技術題與新事業驗證接成可管理節奏。",
    },
    {
      id: "evy-chen",
      name: "Evy Chen",
      role: "處長",
      department: "運籌處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "運籌處主管，適合把產銷、物流與交付限制放回任務推演。",
    },
    {
      id: "douglas-lu",
      name: "Douglas Lu",
      role: "處副總經理",
      department: "行銷發展處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "行銷發展處主管，適合連接商品開發、材質研發、品牌敘事與設計端客戶對口。",
    },
    {
      id: "arthur-kuo",
      name: "Arthur Kuo",
      role: "處總經理",
      department: "業務六處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務六處主管，適合處理廠號系列、Accessories 與業務六處跨線取捨。",
    },
    {
      id: "teresa-hsueh",
      name: "Teresa Hsueh",
      role: "資深經理",
      department: "開發暨技術處 / 樣品研發部",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "樣品研發部 lead，適合把樣品、製版、生管與研發中心的節點串起來。",
    },
    {
      id: "artie-yu",
      name: "Artie Yu",
      role: "經理",
      department: "開發暨技術處 / 特工研發中心",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "特工研發中心 lead，適合處理技術開發、水洗印繡與大貨技術管理。",
    },
    {
      id: "sylvia-chou",
      name: "Sylvia Chou",
      role: "副理",
      department: "開發暨技術處 / 估碼中心",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "估碼中心 lead，適合把報價、大貨與估碼限制納入開發節奏。",
    },
    {
      id: "michael-song",
      name: "Michael Song",
      role: "資深顧問",
      department: "顧問室本部",
      orgUnit: "consulting",
      birthday: "待補",
      style: "顧問室資深角色，適合補上組織記憶、制度觀點與高階風險提醒。",
    },
    {
      id: "annie-wang",
      name: "Annie Wang",
      role: "產區總經理",
      department: "海外產區 / GLR GLS",
      orgUnit: "overseas",
      birthday: "待補",
      style: "海外產區總經理，適合提供產區落地、製造節奏與跨地限制。",
    },
    {
      id: "leo-tsai",
      name: "Leo Tsai",
      role: "產區總經理（兼）",
      department: "海外產區 / 越南；工務研發群協調",
      orgUnit: "overseas",
      birthday: "待補",
      style: "海外產區與工務研發群協調角色，適合把產區現實與研發節奏接上。",
    },
    {
      id: "karen-chou",
      name: "Karen Chou",
      role: "處長",
      department: "業務一處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處主管，ATH/BR/GAP 帳戶主人，適合承接客戶優先級與正式窗口。",
    },
    {
      id: "mandy-chen",
      name: "Mandy Chen",
      role: "處副總經理",
      department: "業務七處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "MK Mandy(ON) = 陳瑋今 Mandy Chen；業務七處主管，管轄 VD/PQA for Old Navy，適合把正式客戶節點與內部準備接起來。",
    },
    {
      id: "ivy-liao",
      name: "Ivy Liao",
      role: "A部 lead + 專案整合",
      department: "業務一處 / A部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處 A部 lead，適合處理 BR/UA/ATH/GS/GO/IPSS 與專案整合。",
    },
    {
      id: "erica-hsu",
      name: "Erica Hsu",
      role: "B部 head",
      department: "業務一處 / B部 GAP GO Knits",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處 B部 head，負責 GAP/GO Knits，適合處理客戶帳戶與開發量產整合。",
    },
    {
      id: "ellen-chang",
      name: "Ellen Chang",
      role: "採購課 head",
      department: "業務一處 / 採購課",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處採購課 head，適合主料、副料與跨品牌採購整合。",
    },
    {
      id: "tania-liu",
      name: "Tania Liu",
      role: "業務統籌",
      department: "業務二處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處統籌，處理 Sanmar、DKS、Calia、VRST 等業務二處主軸。",
    },
    {
      id: "jessica-wang",
      name: "Jessica Wang",
      role: "Development lead",
      department: "業務二處 / A部 DKS-Calia-VRST / Sanmar",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處 A部 Development lead，適合處理 DKS-Calia/VRST 與 Sanmar 開發線。",
    },
    {
      id: "vince-hsu",
      name: "Vince Hsu",
      role: "B部負責人",
      department: "業務二處 / B部 DKS-DSG PG AP Golf",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處 B部負責人，適合處理 DSG/PG/AP/Golf 帳戶與跨線協調。",
    },
    {
      id: "cynthia-fu",
      name: "Cynthia Fu",
      role: "處長",
      department: "業務三處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務三處主管，負責 NET、HLF、A&F、WMT、KOH 等多品牌全處統籌。",
    },
    {
      id: "sasha-lai",
      name: "Sasha Lai",
      role: "處副總經理",
      department: "業務五處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處主管，負責 TGT/GAP_TSD 全處統籌，適合放入 Target 相關任務。",
    },
    {
      id: "ruo-chen",
      name: "Ruo Chen",
      role: "Development lead",
      department: "業務五處 / A部 TGT Performance",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處 A部 TGT Performance Development lead；與 3D 的 ROU 不同人。",
    },
    {
      id: "maggie-tsai",
      name: "Maggie Tsai",
      role: "Production",
      department: "業務五處 / C部 TGT Adult Sleepwear",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處 C部 Production 成員，適合放入 TGT Adult Sleepwear 與新客戶生產線情境。",
    },
    {
      id: "emily-chak",
      name: "Emily Chak",
      role: "執行長室聯絡 + VMI/RnR/CA 專案",
      department: "業務行銷群 / 業務七處（兼）",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "橫跨執行長室聯絡與業務七處專案，適合當高層訊號與專案執行之間的轉接點。",
    },
    {
      id: "melody-lin",
      name: "Melody Lin",
      role: "B部 head + 專案管理",
      department: "業務七處 / B部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務七處 B部 head，兼專案管理與大貨整合，適合 SWIM/FLEECE/FR 與 Beyond Yoga 任務。",
    },
    {
      id: "maggie-chen",
      name: "Maggie Chen",
      role: "Development",
      department: "業務七處 / A部 IPS",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務七處 A部 Development 成員，適合 IPS Studiosmooth/Sleektech 開發情境。",
    },
    {
      id: "yulia-huang",
      name: "Yulia Huang",
      role: "副理",
      department: "行銷發展處 / 材質研發部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "材質研發二課與區域型供應鏈瓜地馬拉兼任角色，適合材質、副料與區域供應鏈情境。",
    },
    {
      id: "brian-lin",
      name: "Brian Lin",
      role: "經理",
      department: "工務處 / 工務管理課",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "工務管理課經理，AI 種子計畫主推者，適合把 AI 轉型變成可執行制度。",
    },
    {
      id: "puli-yu",
      name: "Puli Yu",
      role: "轉投資企業",
      department: "轉投資企業",
      orgUnit: "investment",
      birthday: "待補",
      style: "轉投資企業角色，先作為外部事業連動卡，詳細資料待補。",
    },
    {
      id: "hongren-huang",
      name: "Hongren Huang",
      role: "轉投資企業",
      department: "轉投資企業",
      orgUnit: "investment",
      birthday: "待補",
      style: "轉投資企業角色，先作為外部事業連動卡，詳細資料待補。",
    },
    {
      id: "huihui",
      name: "Huihui",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 平湖",
      orgUnit: "tech-rd",
      birthday: "待補",
      numerology: "?",
      element: "土",
      zodiac: "待補",
      archetype: "待觀察",
      animal: "待補",
      star: "待補",
      style: "目前觀察資料極少，先以保留判斷和接手風險標記為主。",
    }
  ],
  scenarios: [
    {
      id: "delay",
      name: "專案 delay",
      prompt: "交付日期逼近，但關鍵資料還沒到位，需要兩人快速對齊下一步。",
      weights: { clarity: 1.2, speed: 1.1, risk: 1.15, context: .8, warmth: .8, data: 1 }
    },
    {
      id: "vague",
      name: "需求不清楚",
      prompt: "需求描述太抽象，大家以為理解了，但產出方向可能不同。",
      weights: { clarity: 1.25, context: 1.25, risk: 1, speed: .8, warmth: 1, data: .9 }
    },
    {
      id: "demo",
      name: "高層臨時要 demo",
      prompt: "明天要展示，目前只夠做一個可看的版本，必須取捨。",
      weights: { clarity: 1.15, speed: 1.25, risk: 1.1, context: .7, warmth: .8, data: .8 }
    },
    {
      id: "handoff",
      name: "DPC 與數發交接",
      prompt: "需求、資料與系統限制需要在 DPC 與數發之間翻譯清楚。",
      weights: { clarity: 1.15, context: 1.2, data: 1.15, risk: 1, speed: .85, warmth: 1 }
    },
    {
      id: "conflict",
      name: "會議有分歧",
      prompt: "兩邊都覺得自己有道理，但會議正在失焦，需要重新建立共同問題。",
      weights: { warmth: 1.25, context: 1.1, clarity: 1.1, risk: 1.1, speed: .7, data: .9 }
    },
    {
      id: "innovation",
      name: "新想法探索",
      prompt: "要評估一個新 AI 應用是否值得做 prototype。",
      weights: { context: 1.15, speed: 1, data: 1.05, warmth: 1.1, clarity: .95, risk: .85 }
    }
  ],
  jobProfiles: [
    { id: "apparel-dev-sales", group: "業務行銷群", title: "成衣開發業務", unit: "sales-marketing", belongsTo: "各業務處（開發端）", focus: ["開發報價", "調樣", "進單", "作工會議", "樣品跟催"], time: { 訂單開發: 60, 訂單管理: 35, 客供經營: 5 }, competencies: { 溝通協調: "L2", 團隊合作: "L1", 問題解決: "L1-L2" }, traits: ["例行框架", "細心", "開發流程"], conditions: ["成衣產業經驗", "熟悉開發流程"] },
    { id: "bulk-sales", group: "業務行銷群", title: "成衣業務（大貨）", unit: "sales-marketing", belongsTo: "各業務處（大貨端）", focus: ["大貨交期", "產區詢表", "產能確認", "採購串接", "客供維繫"], time: { 訂單管理: 70, 採購串接: 20, 客供經營: 10 }, competencies: { 溝通協調: "L2", 目標導向: "L1-L2", 問題解決: "L2" }, traits: ["負責任", "抗壓", "配合度高"] },
    { id: "v7b-dev-sales", group: "業務行銷群", title: "開發業務（顧家型 V7B）", unit: "sales-marketing", belongsTo: "業務七處 B 部", focus: ["樣品", "報價", "交期", "商機異動", "特殊需求控管"], time: { 客戶服務: 30, 控管訂單: 25, 樣品製作: 15, 特殊需求控管: 15, 報價: 15 }, competencies: { 溝通協調: "L2", 問題解決: "L2" }, traits: ["穩定度高", "抗壓性強"], conditions: ["1-3 年成衣經驗", "TOEIC 785+"] },
    { id: "japanese-sales-indonesia", group: "業務行銷群", title: "日語業務（派駐印尼）", unit: "sales-marketing", belongsTo: "業務六處（派駐業務組）", focus: ["日英文客戶聯繫", "訂單跟催", "驗貨安排", "文件管理", "跨部門資料轉換"], time: { 訂單管理: 95, 驗貨QA協作: 5 }, competencies: { 溝通協調: "L2", 目標導向: "L2" }, traits: ["務實能吃苦", "高工時", "文件細節"], conditions: ["日文 N1/N2", "英文中上", "接受長期派駐"] },
    { id: "material-purchaser-main", group: "業務行銷群", title: "採購管理師（主料）", unit: "sales-marketing", belongsTo: "行銷發展處 / 材質研發部", focus: ["主料 PO", "收料", "TNA 追蹤", "異常處理", "布廠工廠協調"], time: { PO收料: 40, TNA追蹤: 30, 異常處理: 20, 外部協調: 10 }, competencies: { 溝通協調: "L2", 團隊合作: "L1", 問題解決: "L1-L2" }, traits: ["數字敏感", "耐心", "可獨立作業"], conditions: ["布廠經驗", "國貿流程佳"] },
    { id: "material-purchaser-trim", group: "業務行銷群", title: "採購管理師（副料）", unit: "sales-marketing", belongsTo: "行銷發展處 / 材質研發部", focus: ["副料搜尋", "採買", "TNA 追蹤", "異常處理", "副料細節辨識"], time: { 副料搜尋採買: 40, TNA追蹤: 30, 異常處理: 20, 外部協調: 10 }, competencies: { 溝通協調: "L2", 團隊合作: "L1", 問題解決: "L1" }, traits: ["例行工作", "耐心", "細節辨識"], conditions: ["紡織服裝背景", "採購經驗佳"] },
    { id: "technical-designer", group: "開發暨技術處", title: "開發處 TD", unit: "tech-rd", belongsTo: "開發暨技術處 / 技術設計部", focus: ["歐美客戶技術窗口", "pre-fit/尺寸評語", "樣品審核", "內部技術橋梁", "海外樣品中心支援"], time: { 客戶經營: 30, 技術溝通: 35, 樣品審核: 15, 海外出差: 10, 人才培育: 10 }, competencies: { 溝通協調: "L2-L3", 問題解決: "L1-L3", 目標導向: "L2", 團隊合作: "L2" }, traits: ["技術翻譯", "版型判斷", "英文技術文件"], conditions: ["英文技術溝通", "熟悉版型與樣品審核"] },
    { id: "ie-engineer", group: "工務處", title: "IE 工程師", unit: "tech-rd", belongsTo: "工務處 / 工業工程部", focus: ["生產技術資料庫", "產線平衡", "工時評比", "技術包裹", "系統優化"], time: { 現場改善: 40, 技術包裹: 20, 工廠交流: 20, 系統分析: 15, 客戶ME專案: 5 }, competencies: { 問題解決: "L3", 溝通協調: "L2", 團隊合作: "L3", 創新能力: "L2" }, traits: ["拆解瓶頸", "現場改善", "數據效率"], conditions: ["IE/工管/機械/紡織背景佳"] },
    { id: "engineering-project-specialist", group: "工務處", title: "工務管理 專案專員", unit: "tech-rd", belongsTo: "工務處 / 處本部", focus: ["工務管理資訊", "估購送用存資料庫", "KPI", "系統導入", "資料除錯", "產區交流"], time: { 管理資訊規劃: 25, 原物料資料庫: 15, KPI: 15, 系統專案: 15, 資料分析: 10, 產區交流: 10, 出差支援: 10 }, competencies: { 問題解決: "L3-L4", 溝通協調: "L3-L4", 創新能力: "L1-L3", 目標導向: "L1-L2" }, traits: ["系統推動", "跨單位整合", "資料除錯"] },
    { id: "apparel-quality", group: "工務處", title: "成衣品管師", unit: "tech-rd", belongsTo: "工務處 / 品質管理部 / 成衣品管課", focus: ["品質成績分析", "核廠認證", "根因分析", "品質專案", "程序書教材"], time: { 品質分析: 20, 認證準備: 20, 根因分析: 20, 品質專案: 20, 教材培訓: 10, 稽核出差: 10 }, competencies: { 問題解決: "L3", 溝通協調: "L2-L3", 目標導向: "L2", 團隊合作: "L3" }, traits: ["5-why", "魚骨圖", "品質系統", "稽核"] },
    { id: "material-quality", group: "工務處", title: "材質品管師", unit: "tech-rd", belongsTo: "工務處 / 品質管理部 / 材質品管課", focus: ["主料檢驗", "驗貨報告", "檢驗計畫", "面料異常", "供應商廠查"], time: { 主料檢驗: 30, 驗貨安排: 30, 異常追蹤: 20, 供應商廠查: 10, 品質專案: 10 }, competencies: { 目標導向: "L2-L3", 問題解決: "L2", 溝通協調: "L2-L3", 團隊合作: "L2-L3" }, traits: ["檢驗標準", "異常追蹤", "品質證據"] },
    { id: "overseas-accounting", group: "財會管理處", title: "會計管理師（海外）", unit: "ops-mgmt", belongsTo: "財會管理處 / 會計一二三部", focus: ["海外帳務", "合併報表", "成本分析", "稅務法遵", "投資評估", "產區會計培育"], time: { 帳務報表: 20, 成本分析: 15, 稅務法遵: 15, 投資評估: 10, 預算預測: 10 }, competencies: { 問題解決: "L2", 溝通協調: "L2", 目標導向: "L2", 培育部屬: "L2" }, traits: ["英文溝通", "法遵", "財務模擬"], conditions: ["會計背景佳"] },
    { id: "hrd-specialist", group: "總管理處 人力資源部", title: "人才發展課 HRD 專員", unit: "general-mgmt", belongsTo: "總管理處 / 人力資源部 / 人才發展課", focus: ["年度訓練架構", "數位學習平台", "內部講師教材", "員工關係", "人力規劃", "人才識別"], time: { 訓練架構: 25, 數位學習: 20, 教材開發: 20, 員工關係: 10, 人力規劃: 10, 招募識別: 10, 績效高潛: 5 }, competencies: { 目標導向: "L2", 問題解決: "L2-L3", 溝通協調: "L2", 團隊合作: "L1-L2" }, traits: ["知識傳承", "平台推動", "組織優化"] },
    { id: "overseas-hr-admin-lead", group: "海外產區", title: "產區 人事行政主管", unit: "overseas", belongsTo: "海外產區各廠", focus: ["工廠人事行政制度", "總務庶務管理", "廠務協調", "人權驗廠/CSR", "在地團隊帶領"], time: { 人事行政制度: 40, 總務採購架構: 20, 廠務協調: 20, CSR稽核: 15, 團隊帶領: 5 }, competencies: { 問題解決: "L3", 溝通協調: "L2", 創新能力: "L2", 團隊合作: "L3" }, traits: ["結構化", "制度流程", "多元文化彈性"], conditions: ["海外工廠派駐", "東南亞管理經驗", "中文母語"] },
    { id: "overseas-engineering-trainee", group: "海外產區", title: "產區 工務培訓幹部", unit: "overseas", belongsTo: "海外產區各廠", focus: ["生產進度", "隱藏問題", "良率效率", "外籍幹部協作", "產區改善"], time: { 生產追蹤: 40, 數據監控: 30, 跨國協作: 20, 改善專案: 10 }, competencies: { 問題解決: "L3", 溝通協調: "L2", 培育部屬: "L2", 目標導向: "L4" }, traits: ["務實能吃苦", "跨國協作", "穩定度高", "工廠管理職涯"], conditions: ["可長期駐點輪調", "可配合加班"] }
  ],
  competencyLevels: {
    L1: "積極面對基本問題；願意合作；主動了解目標",
    L2: "清楚具體表達想法；快速尋求資源協助；對目標全力以赴",
    L3: "能拆解複雜問題；提供建設性回應；主動參與團隊決議",
    L4: "建立檢核機制；精準理解他人觀點；積極化解衝突"
  },
  orgMissions: [
    {
      id: "fabric-trim-delay",
      name: "Fabric / Trim Lead Time Slip",
      prompt: "主布或副料交期延遲，PP sample、排產和出貨窗口全部被壓縮。玩家必須在五回合內建立替代料、客戶 approval 和產區排程的共同節奏。",
      goal: "鎖定替代料路線、approval owner、產區排程重算與客戶溝通口徑。",
      jobNeeds: ["material-purchaser-main", "material-purchaser-trim", "apparel-dev-sales", "bulk-sales"],
      pressure: { trust: 36, clarity: 30, momentum: 34, friction: 48 },
      weights: { data: 1.25, risk: 1.25, clarity: 1.15, speed: 1.05, context: 1, warmth: .8 }
    },
    {
      id: "pp-sample-loop",
      name: "PP Sample Approval Loop",
      prompt: "PP sample 被退回多輪，fit、construction、material handfeel 和客戶 comment 版本混在一起，bulk production 不能再等。",
      goal: "把退樣原因拆成 fit / construction / material / customer sign-off，決定下一版樣衣的唯一責任人。",
      jobNeeds: ["technical-designer", "apparel-dev-sales", "material-quality", "v7b-dev-sales"],
      pressure: { trust: 38, clarity: 27, momentum: 32, friction: 50 },
      weights: { clarity: 1.35, context: 1.15, risk: 1.2, data: 1.15, speed: .9, warmth: .85 }
    },
    {
      id: "spec-version-drift",
      name: "Spec Version Drift",
      prompt: "業務、技術、工廠各自拿到不同版本 spec，QC 判定和現場做法不一致，rework 正在累積。",
      goal: "建立 single source of truth、版本凍結點、變更通知與工廠 access 規則。",
      jobNeeds: ["technical-designer", "engineering-project-specialist", "apparel-quality", "bulk-sales"],
      pressure: { trust: 34, clarity: 24, momentum: 30, friction: 56 },
      weights: { clarity: 1.4, data: 1.35, risk: 1.2, context: 1.1, speed: .8, warmth: .75 }
    },
    {
      id: "qc-rework-spike",
      name: "QC Rework Spike",
      prompt: "inline inspection 發現縫製、裁片、印繡或尺寸問題，返工量上升，on-time delivery 開始危險。",
      goal: "找到 defect root cause、建立 containment、重排檢驗節點並回報客戶風險。",
      jobNeeds: ["apparel-quality", "material-quality", "ie-engineer", "bulk-sales"],
      pressure: { trust: 33, clarity: 31, momentum: 32, friction: 58 },
      weights: { risk: 1.4, data: 1.25, clarity: 1.15, speed: 1.1, context: .9, warmth: .75 }
    },
    {
      id: "capacity-wip-bottleneck",
      name: "Capacity / WIP Bottleneck",
      prompt: "某條產線 WIP 暴增，瓶頸卡在 sewing、finishing 或 packing；業務仍在追出貨，現場需要取捨。",
      goal: "用 shared timeline 找瓶頸、重排產能、決定是否拆單或改交期。",
      jobNeeds: ["ie-engineer", "overseas-engineering-trainee", "bulk-sales", "engineering-project-specialist"],
      pressure: { trust: 35, clarity: 33, momentum: 28, friction: 52 },
      weights: { speed: 1.25, data: 1.2, risk: 1.2, clarity: 1.1, context: 1, warmth: .8 }
    },
    {
      id: "digital-sample-adoption",
      name: "Digital Sample Adoption",
      prompt: "品牌想縮短 sample loop，但設計、業務、3D、產區對 digital sample 的信任程度不同，必須定義哪些款能用數位樣核准。",
      goal: "建立 digital sample 適用條件、驗收標準、例外處理和客戶教育路徑。",
      jobNeeds: ["technical-designer", "apparel-dev-sales", "engineering-project-specialist"],
      pressure: { trust: 40, clarity: 32, momentum: 38, friction: 42 },
      weights: { context: 1.25, clarity: 1.2, data: 1.15, risk: 1.05, speed: 1, warmth: 1 }
    },
    {
      id: "shipment-booking-crunch",
      name: "Shipment Booking Crunch",
      prompt: "Final inspection、packing、booking 和文件節點互相擠壓，船期或空運成本風險升高。",
      goal: "把 inspection pass、packing readiness、booking cut-off 和客戶承諾放進同一張決策表。",
      jobNeeds: ["bulk-sales", "apparel-quality", "overseas-engineering-trainee", "japanese-sales-indonesia"],
      pressure: { trust: 37, clarity: 32, momentum: 36, friction: 49 },
      weights: { speed: 1.3, risk: 1.2, data: 1.15, clarity: 1.1, context: .9, warmth: .75 }
    },
    {
      id: "costing-margin-squeeze",
      name: "Costing / Margin Squeeze",
      prompt: "客戶 target cost 壓低，但 fabric、labor、freight 或 MOQ 條件不配合；團隊要在報價、設計調整與供應替代間決策。",
      goal: "拆出 cost driver、替代方案、客戶可接受 trade-off 與 margin guardrail。",
      jobNeeds: ["apparel-dev-sales", "bulk-sales", "material-purchaser-main", "overseas-accounting"],
      pressure: { trust: 39, clarity: 34, momentum: 34, friction: 44 },
      weights: { data: 1.3, clarity: 1.2, risk: 1.2, context: 1, speed: .9, warmth: .8 }
    },
    {
      id: "sustainability-traceability",
      name: "Traceability Request",
      prompt: "品牌要求供應鏈透明度、材料來源或永續文件，但資料散在採購、工廠、品管和客戶文件裡。",
      goal: "定義資料責任、文件證據鏈、供應商回覆 SLA 與客戶揭露格式。",
      jobNeeds: ["material-quality", "material-purchaser-main", "apparel-quality", "overseas-hr-admin-lead"],
      pressure: { trust: 38, clarity: 29, momentum: 31, friction: 46 },
      weights: { data: 1.4, risk: 1.2, context: 1.15, clarity: 1.15, speed: .8, warmth: .85 }
    },
    {
      id: "ai-plm-visibility",
      name: "PLM / AI Visibility Pilot",
      prompt: "公司想用 PLM、portal 或 AI dashboard 改善 lead time visibility，但如果只做工具，不改資料 owner 和例外流程，pilot 會空轉。",
      goal: "定義 pilot scope、資料 owner、例外訊號、成功指標與上線後維運責任。",
      jobNeeds: ["engineering-project-specialist", "hrd-specialist", "technical-designer", "overseas-accounting"],
      pressure: { trust: 42, clarity: 31, momentum: 40, friction: 38 },
      weights: { clarity: 1.25, data: 1.25, context: 1.2, speed: 1, risk: 1, warmth: .9 }
    }
  ],
  actionTypes: [
    {
      id: "frame",
      name: "Freeze Spec",
      icon: "◇",
      copy: "凍結目前版次、變更點和客戶 approval 條件。",
      vector: "clarity",
      boosts: { clarity: 16, trust: 3, momentum: 4, friction: -3 }
    },
    {
      id: "bridge",
      name: "Handoff Relay",
      icon: "↔",
      copy: "把上一棒輸入翻成下一棒可執行輸出。",
      vector: "context",
      boosts: { trust: 9, clarity: 9, momentum: 3, friction: -8 }
    },
    {
      id: "prototype",
      name: "Make Sample",
      icon: "▣",
      copy: "做一個可驗證樣本或數位樣，縮短抽象討論。",
      vector: "speed",
      boosts: { momentum: 17, clarity: 5, trust: 2, friction: -1 }
    },
    {
      id: "gate",
      name: "Quality Gate",
      icon: "◆",
      copy: "設 inspection、defect、rework 和放行標準。",
      vector: "risk",
      boosts: { clarity: 10, trust: 4, momentum: 2, friction: -10 }
    },
    {
      id: "evidence",
      name: "Evidence Chain",
      icon: "◎",
      copy: "補齊 spec、sample、照片、測試與供應商回覆證據。",
      vector: "data",
      boosts: { clarity: 8, trust: 8, momentum: 5, friction: -5 }
    },
    {
      id: "align",
      name: "Customer Sync",
      icon: "✦",
      copy: "對齊客戶口徑、風險揭露和可接受 trade-off。",
      vector: "warmth",
      boosts: { trust: 15, clarity: 3, momentum: 1, friction: -12 }
    }
  ],
  strategies: [
    {
      id: "bottom-line",
      name: "結論先行",
      text: "先講要做什麼，再補三個理由。",
      boosts: { clarity: 12, speed: 8, trust: 2, friction: -3 },
      fits: ["delay", "demo"]
    },
    {
      id: "context-brief",
      name: "一頁脈絡 brief",
      text: "用一頁說明背景、限制、目標和待決策點。",
      boosts: { clarity: 8, context: 12, trust: 6, friction: -5 },
      fits: ["vague", "handoff", "innovation"]
    },
    {
      id: "owner-risk",
      name: "拆 owner / deadline / risk",
      text: "把模糊討論拆成負責人、期限和風險。",
      boosts: { clarity: 14, trust: 4, momentum: 8, friction: -2 },
      fits: ["delay", "handoff", "demo"]
    },
    {
      id: "data-proof",
      name: "用數據說服",
      text: "先拿證據和樣本，再要求決策。",
      boosts: { clarity: 8, trust: 8, momentum: 4, friction: -3 },
      fits: ["handoff", "innovation"]
    },
    {
      id: "private-align",
      name: "先私下對齊",
      text: "先一對一校準，再進大會議。",
      boosts: { trust: 12, clarity: 4, momentum: 2, friction: -10 },
      fits: ["conflict", "vague"]
    },
    {
      id: "prototype",
      name: "轉成 prototype",
      text: "用可看的小版本取代長時間抽象辯論。",
      boosts: { momentum: 14, clarity: 7, trust: 3, friction: -1 },
      fits: ["innovation", "demo"]
    },
    {
      id: "options",
      name: "把問題變選項題",
      text: "提供 A/B/C 選項和各自代價，讓對方比較好決定。",
      boosts: { clarity: 12, momentum: 8, trust: 5, friction: -4 },
      fits: ["vague", "conflict", "delay"]
    },
    {
      id: "uncertainty",
      name: "先承認不確定",
      text: "先說哪些已知、哪些未知，再決定要補什麼資料。",
      boosts: { trust: 10, clarity: 7, momentum: 2, friction: -6 },
      fits: ["vague", "innovation", "conflict"]
    }
  ],
  elementRelations: {
    "木-火": "相生：願景能推動速度，適合開新局。",
    "火-土": "相生：推動力能落成流程，但要防止過度催促。",
    "土-金": "相生：現實感能長出標準，適合定規格。",
    "金-水": "相生：標準與資訊流能形成判斷，適合做系統化分析。",
    "水-木": "相生：洞察滋養新方向，適合探索。",
    "木-土": "相剋：擴張遇到現實限制，要先講取捨。",
    "土-水": "相剋：穩定與流動拉扯，要用明確邊界保護彈性。",
    "水-火": "相剋：靈感與速度易互相消耗，需要節奏管理。",
    "火-金": "相剋：推動力碰到標準，摩擦高但能打磨決策。",
    "金-木": "相剋：標準會修剪願景，適合做策略取捨。"
  }
};



