const GAME_DATA = {
  orgUnits: [
    {
      id: "ceo",
      name: "公司頂層",
      tagline: "董事長、執行長、最高層決策與跨群取捨",
      capability: ["決策授權", "資源取捨", "跨群優先級"],
      risk: "離現場太遠時，會把複雜問題壓成口號。",
      counters: ["authority", "tradeoff", "scope"],
      links: ["sales-marketing", "tech-rd", "newbiz", "general-mgmt"]
    },
    {
      id: "consulting",
      name: "顧問室本部",
      tagline: "資深顧問、制度記憶與高階輔助判斷",
      capability: ["制度記憶", "高階諮詢", "風險提醒"],
      risk: "若沒有接到一線問題，容易停留在原則層。",
      counters: ["memory", "advice", "review"],
      links: ["ceo", "general-mgmt"]
    },
    {
      id: "general-mgmt",
      name: "總管理處",
      tagline: "公司級管理節奏、AI 種子計畫與跨群推動",
      capability: ["管理節奏", "變革推動", "跨群協調"],
      risk: "變革如果只停在倡議，會缺少落地隊形。",
      counters: ["change", "seed", "cadence"],
      links: ["ceo", "ops-mgmt", "tech-rd", "newbiz"]
    },
    {
      id: "sales-marketing",
      name: "業務行銷群",
      tagline: "業務一至七處、行銷發展處、品牌與客戶訊號",
      capability: ["客戶情境", "品牌需求", "商業化路徑"],
      risk: "客戶語言若沒有翻成產品規格，會在交接時失真。",
      counters: ["brand", "client", "market"],
      links: ["ceo", "newbiz", "tech-rd"]
    },
    {
      id: "ops-mgmt",
      name: "營運管理群",
      tagline: "資訊、財會、平台治理與營運支撐",
      capability: ["系統治理", "財務約束", "資料基礎"],
      risk: "若太晚進場，產品會先長出不可維護的流程。",
      counters: ["system", "finance", "governance"],
      links: ["general-mgmt", "newbiz", "tech-rd"]
    },
    {
      id: "tech-rd",
      name: "工務研發群",
      tagline: "開發暨技術處、工務處、運籌處；3D研發中心隸屬開發暨技術處",
      capability: ["研發落地", "3D 標準", "品質閘門"],
      risk: "需求邊界不清時，會用高執行力做出錯方向；知識鎖倉會形成單點風險。",
      counters: ["rd", "3d", "gate"],
      links: ["newbiz", "sales-marketing", "ops-mgmt"]
    },
    {
      id: "overseas",
      name: "海外產區",
      tagline: "GLR/GLS、越南與跨產區製造現場",
      capability: ["產區落地", "製造限制", "跨地回饋"],
      risk: "若只用台北視角看現場，會誤判地理成本與執行限制。",
      counters: ["factory", "region", "feedback"],
      links: ["tech-rd", "sales-marketing"]
    },
    {
      id: "newbiz",
      name: "新事業發展群",
      tagline: "數位產品發展中心、智慧紡織發展中心",
      capability: ["產品實驗", "GTM", "AI prototype"],
      risk: "沒有真實 demo 與回饋迴路時，聲量無法轉成採用。",
      counters: ["product", "ai", "feedback"],
      links: ["ceo", "tech-rd", "sales-marketing", "ops-mgmt"]
    },
    {
      id: "investment",
      name: "轉投資企業",
      tagline: "轉投資角色與外部事業連結",
      capability: ["外部資源", "事業連動", "策略彈性"],
      risk: "若和主組織任務沒有清楚接口，容易只剩名義連線。",
      counters: ["venture", "external", "link"],
      links: ["ceo"]
    },
    {
      id: "pending",
      name: "Makalot / 待定位",
      tagline: "人名先掛上，組織歸屬待 makalot-org 校正",
      capability: ["待補"],
      risk: "不能用單場會議情境推定正式部門。",
      counters: ["unknown"],
      links: ["ceo", "sales-marketing", "tech-rd", "newbiz"]
    }
  ],
  orgDirectory: [
    { id: "board", unit: "ceo", name: "董事會", members: [] },
    { id: "audit-office", unit: "ceo", name: "稽核室", members: [] },
    { id: "ceo-office", unit: "ceo", name: "執行長 / 公司頂層", members: ["alex"] },
    { id: "decision-integration-committee", unit: "ceo", name: "決策整合委員會", members: [] },
    { id: "audit-committee", unit: "ceo", name: "審計委員會", members: [] },
    { id: "compensation-committee", unit: "ceo", name: "薪資報酬委員會", members: [] },
    { id: "sustainability-committee", unit: "ceo", name: "永續委員會", members: [] },
    { id: "consulting-office", unit: "consulting", name: "顧問室本部", members: ["michael-song"] },
    { id: "general-office", unit: "general-mgmt", name: "總管理處", members: ["mandy-huang"] },
    { id: "sales-group", unit: "sales-marketing", name: "業務行銷群", members: ["tiffany-sung"] },
    { id: "sales-1", unit: "sales-marketing", name: "業務一處", members: ["karen-chou", "ivy-liao", "erica-hsu", "ellen-chang"] },
    { id: "sales-2", unit: "sales-marketing", name: "業務二處", members: ["tania-liu", "jessica-wang", "vince-hsu", "erica-chang"] },
    { id: "sales-3", unit: "sales-marketing", name: "業務三處", members: ["cynthia-fu"] },
    { id: "sales-5", unit: "sales-marketing", name: "業務五處", members: ["sasha-lai", "ruo-chen", "maggie-tsai"] },
    { id: "sales-6", unit: "sales-marketing", name: "業務六處", members: ["arthur-kuo"] },
    { id: "sales-7", unit: "sales-marketing", name: "業務七處", members: ["mandy-chen", "emily-chak", "melody-lin", "hazel-lin", "maggie-chen"] },
    { id: "marketing-dev", unit: "sales-marketing", name: "行銷發展處", members: ["douglas-lu", "yulia-huang"] },
    { id: "finance-admin-office", unit: "ops-mgmt", name: "財會管理處", members: ["christine-wen"] },
    { id: "accounting-1", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計一部", members: [] },
    { id: "accounting-2", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計二部", members: [] },
    { id: "accounting-3", unit: "ops-mgmt", parent: "finance-admin-office", name: "會計三部", members: [] },
    { id: "finance-dept", unit: "ops-mgmt", parent: "finance-admin-office", name: "財務部", members: [] },
    { id: "stock-affairs-project", unit: "ops-mgmt", parent: "finance-admin-office", name: "股務暨專案組", members: [] },
    { id: "risk-investment-project", unit: "ops-mgmt", parent: "finance-admin-office", name: "風控/投資評估專案小組", members: [] },
    { id: "overseas-finance-investment", unit: "ops-mgmt", parent: "finance-admin-office", name: "海外財會組織/轉投資", members: [] },
    { id: "it-office", unit: "ops-mgmt", name: "資訊處", members: ["benjamin-hsieh"] },
    { id: "app-development", unit: "ops-mgmt", parent: "it-office", name: "應用開發部", members: [] },
    { id: "app-dev-1", unit: "ops-mgmt", parent: "app-development", name: "開發I課", members: [] },
    { id: "app-dev-2", unit: "ops-mgmt", parent: "app-development", name: "開發II課", members: [] },
    { id: "app-dev-3", unit: "ops-mgmt", parent: "app-development", name: "開發III課", members: [] },
    { id: "app-dev-4", unit: "ops-mgmt", parent: "app-development", name: "開發IV課", members: [] },
    { id: "erp-development", unit: "ops-mgmt", parent: "it-office", name: "ERP開發部", members: [] },
    { id: "system-operations", unit: "ops-mgmt", parent: "it-office", name: "系統營運部", members: [] },
    { id: "security-group", unit: "ops-mgmt", parent: "system-operations", name: "資安組", members: [] },
    { id: "system-maintenance", unit: "ops-mgmt", parent: "system-operations", name: "系統維護課", members: [] },
    { id: "digital-transformation", unit: "ops-mgmt", parent: "it-office", name: "數位轉型部", members: [] },
    { id: "dt-engineering", unit: "ops-mgmt", parent: "digital-transformation", name: "工程師群", members: [] },
    { id: "ai-ops-project", unit: "ops-mgmt", parent: "digital-transformation", name: "AI應用/營運與專案管理", members: [] },
    { id: "engineering-system", unit: "ops-mgmt", parent: "it-office", name: "工務系統部", members: [] },
    { id: "intelligent-application", unit: "ops-mgmt", parent: "it-office", name: "智能應用組", members: [] },
    { id: "software-architecture-committee", unit: "ops-mgmt", parent: "it-office", name: "軟體架構委員會", members: [] },
    { id: "api-review", unit: "ops-mgmt", parent: "software-architecture-committee", name: "API審查小組", members: [] },
    { id: "data-governance", unit: "ops-mgmt", parent: "software-architecture-committee", name: "資料治理小組", members: [] },
    { id: "dev-tech", unit: "tech-rd", name: "開發暨技術處", members: ["celia-hsu"] },
    { id: "rd-3d", unit: "tech-rd", parent: "dev-tech", name: "3D研發中心", members: ["elly", "karen", "adia", "yoko", "debbie", "chieh", "sixian", "rou", "jean", "yota", "jan", "huihui", "tinley", "rock"] },
    { id: "chiayi-sample-center", unit: "tech-rd", parent: "dev-tech", name: "嘉義樣品中心", members: [] },
    { id: "costing-center", unit: "tech-rd", parent: "dev-tech", name: "估碼中心", members: [] },
    { id: "technical-design", unit: "tech-rd", parent: "dev-tech", name: "技術設計部", members: ["lillian-lin"] },
    { id: "special-rd", unit: "tech-rd", parent: "dev-tech", name: "特工研發中心", members: ["artie-yu"] },
    { id: "dev-logistics-section", unit: "tech-rd", parent: "dev-tech", name: "運籌課", members: [] },
    { id: "sample-rd", unit: "tech-rd", parent: "dev-tech", name: "樣品研發部", members: ["teresa-hsueh"] },
    { id: "engineering-office", unit: "tech-rd", name: "工務處", members: [] },
    { id: "engineering-hq", unit: "tech-rd", parent: "engineering-office", name: "工務處處本部", members: ["anne-hu", "brian-lin", "evy-chen"] },
    { id: "fabric-inspection-team", unit: "tech-rd", parent: "engineering-office", name: "驗布團隊", members: [] },
    { id: "bulk-technician-team", unit: "tech-rd", parent: "engineering-office", name: "大貨技師團隊", members: [] },
    { id: "industrial-engineering", unit: "tech-rd", parent: "engineering-office", name: "工業工程部", members: [] },
    { id: "quality-management", unit: "tech-rd", parent: "engineering-office", name: "品質管理部", members: [] },
    { id: "logistics-office", unit: "tech-rd", name: "運籌處", members: [] },
    { id: "logistics-management", unit: "tech-rd", parent: "logistics-office", name: "物流管理部", members: [] },
    { id: "export-management", unit: "tech-rd", parent: "logistics-management", name: "出口管理課", members: [] },
    { id: "import-docs", unit: "tech-rd", parent: "logistics-management", name: "進口文件課", members: [] },
    { id: "production-sales-management", unit: "tech-rd", parent: "logistics-office", name: "產銷管理部", members: [] },
    { id: "digital-product", unit: "newbiz", name: "數位產品發展中心", members: ["alex", "elly", "alan", "andy", "vanessa", "doris", "emily", "dianne"] },
    { id: "smart-textile", unit: "newbiz", name: "智慧紡織發展中心", members: ["wayi-tsai"] },
    { id: "overseas-region", unit: "overseas", name: "海外產區", members: ["annie-wang", "leo-tsai"] },
    { id: "investment-companies", unit: "investment", name: "轉投資企業", members: ["puli-yu", "hongren-huang"] },
    { id: "pending-members", unit: "pending", name: "待 makalot-org 定位", members: ["jessica", "rosa", "ruochen", "maggie", "sharon", "winnie"] }
  ],
  members: [
    {
      id: "adia",
      name: "Adia",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1991-10-28",
      numerology: 4,
      element: "金",
      zodiac: "天蠍座",
      archetype: "建設者",
      animal: "羊",
      star: "天相星",
      style: "重視穩定與交付，適合用清楚範圍和檢核點對齊。",
      distilled: { confidence: "中", turns: 54, traits: ["短句確認", "現場補位", "快速接話"] },
      vectors: { clarity: 82, context: 62, speed: 54, risk: 76, data: 72, warmth: 58 }
    },
    {
      id: "alan",
      name: "Alan Liu",
      localName: "劉俊毅",
      role: "資深3D技師",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1992-01-31",
      numerology: 8,
      element: "水",
      zodiac: "水瓶座",
      archetype: "成就者",
      animal: "猴",
      star: "天同星",
      style: "偏好有目標、有邊界的討論，能接受新方法但需要看到產出。",
      distilled: { confidence: "高", turns: 178, traits: ["進度核對", "工程交接", "問題回覆"] },
      vectors: { clarity: 76, context: 58, speed: 70, risk: 55, data: 68, warmth: 50 }
    },
    {
      id: "alex",
      name: "Alex Chou",
      localName: "周心鵬",
      role: "CEO",
      department: "公司頂層 / 執行長",
      orgUnit: "ceo",
      birthday: "1984-05-01",
      numerology: 1,
      element: "木",
      zodiac: "金牛座",
      archetype: "領導者",
      animal: "鼠",
      star: "天府星",
      style: "適合用願景、取捨與商業結果對話，避免陷入過細的執行枝節。",
      vectors: { clarity: 88, context: 70, speed: 68, risk: 72, data: 66, warmth: 52 }
    },
    {
      id: "andy",
      name: "Andy Liu",
      localName: "柳宥良",
      role: "3D技師",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1996-11-01",
      numerology: 1,
      element: "火",
      zodiac: "天蠍座",
      archetype: "領導者",
      animal: "鼠",
      star: "七殺星",
      style: "推進感強，適合給明確目標和可立即動手的切入點。",
      vectors: { clarity: 74, context: 48, speed: 82, risk: 50, data: 60, warmth: 48 }
    },
    {
      id: "chieh",
      name: "Chieh",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1990-03-24",
      numerology: 1,
      element: "土",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "馬",
      star: "破軍星",
      style: "能快速開局，也容易被模糊需求消耗；最好把問題變成選項。",
      distilled: { confidence: "低", turns: 18, traits: ["進度回報", "先解眼前問題", "實作導向"] },
      vectors: { clarity: 80, context: 45, speed: 84, risk: 46, data: 56, warmth: 44 }
    },
    {
      id: "debbie",
      name: "Debbie",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1985-04-01",
      numerology: 1,
      element: "木",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "牛",
      star: "廉貞星",
      style: "適合直接講重點和預期成果，節奏拖太長會降低耐心。",
      vectors: { clarity: 78, context: 50, speed: 82, risk: 54, data: 58, warmth: 45 }
    },
    {
      id: "dianne",
      name: "Dianne Chen",
      localName: "陳亭妤",
      role: "行銷專員",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1993-03-18",
      numerology: 7,
      element: "水",
      zodiac: "雙魚座",
      archetype: "探索者",
      animal: "雞",
      star: "太陰星",
      style: "擅長感受脈絡和受眾反應，適合先對齊語氣再進入任務。",
      vectors: { clarity: 62, context: 84, speed: 52, risk: 64, data: 62, warmth: 78 }
    },
    {
      id: "doris",
      name: "Doris Lin",
      localName: "林雅庭",
      role: "專案專員",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1995-10-22",
      numerology: 11,
      element: "木",
      zodiac: "天秤座",
      archetype: "啟示者",
      animal: "豬",
      star: "天同星",
      style: "在協調和美感判斷上敏銳，適合用共識框架推進。",
      distilled: { confidence: "高", turns: 53, traits: ["deadline 意識", "流程協調", "友善收斂"] },
      vectors: { clarity: 64, context: 78, speed: 54, risk: 60, data: 58, warmth: 82 }
    },
    {
      id: "elly",
      name: "Elly Cheng",
      localName: "程麗如",
      role: "數位產品開發總監（兼3D研發中心）",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1983-04-27",
      numerology: 7,
      element: "木",
      zodiac: "金牛座",
      archetype: "探索者",
      animal: "豬",
      star: "武曲星",
      style: "偏好結論有立場、脈絡夠完整、能回答 so what 的討論。",
      distilled: { confidence: "高", turns: 779, traits: ["高頻提問", "脈絡整合", "行動收斂"] },
      vectors: { clarity: 86, context: 88, speed: 66, risk: 70, data: 78, warmth: 56 }
    },
    {
      id: "emily",
      name: "Emily Shen",
      localName: "申書璇",
      role: "行銷專員",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1994-04-29",
      numerology: 11,
      element: "木",
      zodiac: "金牛座",
      archetype: "啟示者",
      animal: "狗",
      star: "廉貞星",
      style: "重視品質與穩定判斷，適合用具體案例和明確標準溝通。",
      distilled: { confidence: "高", turns: 125, traits: ["品牌想像", "視覺語言", "教學轉譯"] },
      vectors: { clarity: 78, context: 66, speed: 52, risk: 74, data: 72, warmth: 62 }
    },
    {
      id: "jan",
      name: "Jan",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 嘉義",
      orgUnit: "tech-rd",
      birthday: "1996-02-26",
      numerology: 8,
      element: "火",
      zodiac: "雙魚座",
      archetype: "成就者",
      animal: "鼠",
      star: "紫微星",
      style: "能把情緒感知轉成成果導向，適合先說目標再保留彈性。",
      distilled: { confidence: "低", turns: 12, traits: ["進度回報", "確認追問", "客戶回饋"] },
      vectors: { clarity: 72, context: 70, speed: 62, risk: 58, data: 62, warmth: 76 }
    },
    {
      id: "jean",
      name: "Jean",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "2002-05-21",
      numerology: 3,
      element: "水",
      zodiac: "雙子座",
      archetype: "表達者",
      animal: "馬",
      star: "七殺星",
      style: "反應快、點子多，適合用短迭代和可視化產物聚焦。",
      distilled: { confidence: "低", turns: 12, traits: ["執行回報", "版型比較", "做工調整"] },
      vectors: { clarity: 58, context: 56, speed: 86, risk: 42, data: 54, warmth: 66 }
    },
    {
      id: "karen",
      name: "Karen King",
      role: "副理",
      department: "3D研發中心",
      orgUnit: "tech-rd",
      birthday: "1986-04-22",
      numerology: 5,
      element: "火",
      zodiac: "金牛座",
      archetype: "自由者",
      animal: "虎",
      star: "七殺星",
      style: "能快速判斷現場可不可行，適合用決策選項和風險交換溝通。",
      distilled: { confidence: "高", turns: 259, traits: ["現場判斷", "催動進度", "直接追問"] },
      vectors: { clarity: 82, context: 56, speed: 74, risk: 68, data: 62, warmth: 50 }
    },
    {
      id: "rock",
      name: "Rock Chu",
      role: "專員",
      department: "3D研發中心 / 數位布料",
      orgUnit: "tech-rd",
      birthday: "1990-01-28",
      numerology: 3,
      element: "金",
      zodiac: "水瓶座",
      archetype: "表達者",
      animal: "馬",
      star: "天機星",
      style: "適合討論系統關係與替代方案，溝通時要給空間發散再收斂。",
      distilled: { confidence: "低", turns: 12, traits: ["支援補位", "工具操作", "流程整理"] },
      vectors: { clarity: 64, context: 66, speed: 76, risk: 50, data: 68, warmth: 60 }
    },
    {
      id: "rou",
      name: "ROU",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1999-04-04",
      numerology: 9,
      element: "火",
      zodiac: "牡羊座",
      archetype: "人道者",
      animal: "兔",
      star: "貪狼星",
      style: "對人和內容氛圍敏銳，適合給舞台、方向和清楚的成功樣貌。",
      distilled: { confidence: "低", turns: 19, traits: ["內容跟催", "語氣回報", "社群節奏"] },
      vectors: { clarity: 66, context: 68, speed: 78, risk: 48, data: 54, warmth: 78 }
    },
    {
      id: "sixian",
      name: "Sixian",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1990-05-02",
      numerology: 8,
      element: "金",
      zodiac: "金牛座",
      archetype: "成就者",
      animal: "馬",
      star: "太陰星",
      style: "穩定、務實、重視成果，適合用明確 deliverable 對齊。",
      distilled: { confidence: "低", turns: 15, traits: ["支援排程", "確認召集", "短句回覆"] },
      vectors: { clarity: 84, context: 60, speed: 58, risk: 78, data: 74, warmth: 56 }
    },
    {
      id: "tinley",
      name: "Tinley Wang",
      role: "專員",
      department: "3D研發中心 / 數位布料",
      orgUnit: "tech-rd",
      birthday: "1995-10-18",
      numerology: 7,
      element: "木",
      zodiac: "天秤座",
      archetype: "探索者",
      animal: "豬",
      star: "紫微星",
      style: "適合處理探索型議題，先給脈絡和判斷準則會更穩。",
      distilled: { confidence: "中", turns: 42, traits: ["詢問可行性", "風險感知", "彈性配合"] },
      vectors: { clarity: 68, context: 82, speed: 54, risk: 62, data: 66, warmth: 72 }
    },
    {
      id: "vanessa",
      name: "Vanessa Chou",
      localName: "周嗣萱",
      role: "行銷策略總監",
      department: "數位產品發展中心",
      orgUnit: "newbiz",
      birthday: "1984-12-25",
      numerology: 5,
      element: "木",
      zodiac: "摩羯座",
      archetype: "自由者",
      animal: "鼠",
      star: "巨門星",
      style: "擅長把自由度和現實限制拉在一起，適合討論優先級與資源取捨。",
      distilled: { confidence: "高", turns: 87, traits: ["脈絡說明", "目的重述", "跨方協調"] },
      vectors: { clarity: 84, context: 68, speed: 62, risk: 82, data: 70, warmth: 54 }
    },
    {
      id: "yoko",
      name: "Yoko",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 台北",
      orgUnit: "tech-rd",
      birthday: "1989-07-30",
      numerology: 1,
      element: "金",
      zodiac: "獅子座",
      archetype: "領導者",
      animal: "蛇",
      star: "巨門星",
      style: "適合用明確主張和成果舞台溝通，避免只給零碎任務。",
      distilled: { confidence: "中", turns: 71, traits: ["款式進度", "資源需求", "變更回報"] },
      vectors: { clarity: 76, context: 54, speed: 76, risk: 58, data: 62, warmth: 62 }
    },
    {
      id: "yota",
      name: "Yota",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 嘉義",
      orgUnit: "tech-rd",
      birthday: "1999-04-02",
      numerology: 7,
      element: "土",
      zodiac: "牡羊座",
      archetype: "探索者",
      animal: "兔",
      star: "天府星",
      style: "適合做探索與落地之間的橋接，需要清楚問題和可試驗範圍。",
      distilled: { confidence: "中", turns: 38, traits: ["進度更新", "急件處理", "執行排程"] },
      vectors: { clarity: 72, context: 72, speed: 72, risk: 58, data: 72, warmth: 58 }
    },
    {
      id: "celia-hsu",
      name: "Celia Hsu",
      role: "處副總經理",
      department: "開發暨技術處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "開發暨技術處正式主管，3D研發中心直屬上級；適合處理研發資源、品質標準與跨部門優先級。",
      distilled: { confidence: "中", turns: 3, traits: ["正式組織", "開發技術", "資料待補"] },
      vectors: { clarity: 62, context: 58, speed: 58, risk: 62, data: 58, warmth: 58 }
    },
    {
      id: "jessica",
      name: "Jessica",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Workshop 與 GTM 情境中的內部協作角色，適合放在活動設計、受眾定位與收斂討論。",
      distilled: { confidence: "低", turns: 2, traits: ["workshop", "活動定位", "資料待補"] },
      vectors: { clarity: 68, context: 76, speed: 56, risk: 62, data: 60, warmth: 70 }
    },
    {
      id: "rosa",
      name: "Rosa",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Workshop 情境中出現的內部角色，先作為品牌互動與內容支援卡。",
      distilled: { confidence: "低", turns: 1, traits: ["workshop", "內容支援", "資料待補"] },
      vectors: { clarity: 60, context: 74, speed: 58, risk: 56, data: 56, warmth: 76 }
    },
    {
      id: "ruochen",
      name: "Ruo Chen",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "與 ROU / 林芓葇不同人，先作為 Workshop project 互動與需求理解角色。",
      distilled: { confidence: "低", turns: 2, traits: ["workshop", "project理解", "需避免同名混淆"] },
      vectors: { clarity: 64, context: 78, speed: 54, risk: 64, data: 60, warmth: 72 }
    },
    {
      id: "hazel-lin",
      name: "Hazel Lin",
      role: "A部 Development lead",
      department: "業務七處 / A部 IPS",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，適合承接市場觀察、開發素材與款式方向整理。",
      distilled: { confidence: "低", turns: 1, traits: ["dev trip", "市場訊號", "資料待補"] },
      vectors: { clarity: 66, context: 78, speed: 62, risk: 58, data: 64, warmth: 66 }
    },
    {
      id: "lillian-lin",
      name: "Lillian Lin",
      role: "資深經理",
      department: "開發暨技術處 / 技術設計部",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，先作為開發 brief、樣布與款式同步角色。",
      distilled: { confidence: "低", turns: 1, traits: ["dev trip", "開發brief", "資料待補"] },
      vectors: { clarity: 68, context: 72, speed: 60, risk: 62, data: 62, warmth: 62 }
    },
    {
      id: "maggie",
      name: "Maggie",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "Seoul Dev Trip 內部成員，適合協助把客戶方向轉成素材需求與下一步行動。",
      distilled: { confidence: "低", turns: 1, traits: ["dev trip", "素材需求", "資料待補"] },
      vectors: { clarity: 64, context: 74, speed: 64, risk: 58, data: 60, warmth: 68 }
    },
    {
      id: "erica-chang",
      name: "Erica Chang",
      role: "專員",
      department: "業務二處 / A部 DKS-Calia-VRST",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，適合處理 2D 定位、版型與工差風險。",
      distilled: { confidence: "低", turns: 1, traits: ["2D定位", "供應鏈", "資料待補"] },
      vectors: { clarity: 72, context: 58, speed: 62, risk: 78, data: 70, warmth: 52 }
    },
    {
      id: "sharon",
      name: "Sharon",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，先作為版型與花位交接支援卡。",
      distilled: { confidence: "低", turns: 1, traits: ["2D定位", "花位交接", "資料待補"] },
      vectors: { clarity: 68, context: 60, speed: 64, risk: 74, data: 68, warmth: 56 }
    },
    {
      id: "winnie",
      name: "Winnie",
      role: "專員",
      department: "Makalot / 待定位",
      orgUnit: "pending",
      birthday: "待補",
      style: "DICKS 定位裁印花會議中的內部角色，適合補足工廠端規格確認與量產風險視角。",
      distilled: { confidence: "低", turns: 1, traits: ["2D定位", "量產風險", "資料待補"] },
      vectors: { clarity: 66, context: 62, speed: 60, risk: 76, data: 70, warmth: 58 }
    },
    {
      id: "mandy-huang",
      name: "Mandy Huang",
      role: "群總經理",
      department: "總管理處 / 營運管理群（兼）",
      orgUnit: "general-mgmt",
      birthday: "待補",
      style: "AI 種子計畫發起者，適合啟動跨群變革、定義推動節奏與組織級授權。",
      vectors: { clarity: 82, context: 78, speed: 64, risk: 72, data: 70, warmth: 62 }
    },
    {
      id: "tiffany-sung",
      name: "Tiffany Sung",
      role: "群總經理",
      department: "業務行銷群",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務行銷群最高主管，適合把客戶訊號、品牌方向與商業取捨拉回決策桌。",
      vectors: { clarity: 84, context: 76, speed: 66, risk: 74, data: 68, warmth: 58 }
    },
    {
      id: "anne-hu",
      name: "Anne Hu",
      role: "處長",
      department: "工務處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "工務處主管，負責品質、工業工程與大貨技師團隊的現場落地判斷。",
      vectors: { clarity: 78, context: 64, speed: 70, risk: 82, data: 72, warmth: 52 }
    },
    {
      id: "benjamin-hsieh",
      name: "Benjamin Hsieh",
      role: "處長",
      department: "資訊處",
      orgUnit: "ops-mgmt",
      birthday: "待補",
      style: "資訊處主管，適合處理系統、權限、資料治理與 AI 工具落地支援。",
      vectors: { clarity: 76, context: 66, speed: 62, risk: 80, data: 84, warmth: 50 }
    },
    {
      id: "christine-wen",
      name: "Christine Wen",
      role: "處副總經理",
      department: "財會管理處",
      orgUnit: "ops-mgmt",
      birthday: "待補",
      style: "財會管理處主管，適合在新產品、展會與投資議題中補上成本、預算與風險約束。",
      vectors: { clarity: 78, context: 64, speed: 56, risk: 86, data: 82, warmth: 52 }
    },
    {
      id: "wayi-tsai",
      name: "Wayi Tsai",
      role: "資深經理",
      department: "智慧紡織發展中心",
      orgUnit: "newbiz",
      birthday: "待補",
      style: "智慧紡織發展中心 lead，適合把專案線、技術題與新事業驗證接成可管理節奏。",
      vectors: { clarity: 76, context: 72, speed: 64, risk: 70, data: 76, warmth: 58 }
    },
    {
      id: "evy-chen",
      name: "Evy Chen",
      role: "處長",
      department: "運籌處",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "運籌處主管，適合把產銷、物流與交付限制放回任務推演。",
      vectors: { clarity: 74, context: 68, speed: 68, risk: 76, data: 72, warmth: 54 }
    },
    {
      id: "douglas-lu",
      name: "Douglas Lu",
      role: "處副總經理",
      department: "行銷發展處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "行銷發展處主管，適合連接商品開發、材質研發、品牌敘事與設計端客戶對口。",
      vectors: { clarity: 82, context: 80, speed: 64, risk: 68, data: 66, warmth: 60 }
    },
    {
      id: "arthur-kuo",
      name: "Arthur Kuo",
      role: "處總經理",
      department: "業務六處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務六處主管，適合處理廠號系列、Accessories 與業務六處跨線取捨。",
      vectors: { clarity: 78, context: 66, speed: 66, risk: 74, data: 68, warmth: 54 }
    },
    {
      id: "teresa-hsueh",
      name: "Teresa Hsueh",
      role: "資深經理",
      department: "開發暨技術處 / 樣品研發部",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "樣品研發部 lead，適合把樣品、製版、生管與研發中心的節點串起來。",
      vectors: { clarity: 76, context: 68, speed: 70, risk: 76, data: 70, warmth: 56 }
    },
    {
      id: "artie-yu",
      name: "Artie Yu",
      role: "經理",
      department: "開發暨技術處 / 特工研發中心",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "特工研發中心 lead，適合處理技術開發、水洗印繡與大貨技術管理。",
      vectors: { clarity: 74, context: 62, speed: 72, risk: 78, data: 70, warmth: 52 }
    },
    {
      id: "sylvia-chou",
      name: "Sylvia Chou",
      role: "副理",
      department: "開發暨技術處 / 估碼中心",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "估碼中心 lead，適合把報價、大貨與估碼限制納入開發節奏。",
      vectors: { clarity: 74, context: 64, speed: 66, risk: 78, data: 74, warmth: 54 }
    },
    {
      id: "michael-song",
      name: "Michael Song",
      role: "資深顧問",
      department: "顧問室本部",
      orgUnit: "consulting",
      birthday: "待補",
      style: "顧問室資深角色，適合補上組織記憶、制度觀點與高階風險提醒。",
      vectors: { clarity: 82, context: 82, speed: 48, risk: 84, data: 76, warmth: 56 }
    },
    {
      id: "annie-wang",
      name: "Annie Wang",
      role: "產區總經理",
      department: "海外產區 / GLR GLS",
      orgUnit: "overseas",
      birthday: "待補",
      style: "海外產區總經理，適合提供產區落地、製造節奏與跨地限制。",
      vectors: { clarity: 76, context: 76, speed: 68, risk: 78, data: 70, warmth: 58 }
    },
    {
      id: "leo-tsai",
      name: "Leo Tsai",
      role: "產區總經理（兼）",
      department: "海外產區 / 越南；工務研發群協調",
      orgUnit: "overseas",
      birthday: "待補",
      style: "海外產區與工務研發群協調角色，適合把產區現實與研發節奏接上。",
      vectors: { clarity: 78, context: 74, speed: 68, risk: 80, data: 72, warmth: 54 }
    },
    {
      id: "karen-chou",
      name: "Karen Chou",
      role: "處長",
      department: "業務一處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處主管，ATH/BR/GAP 帳戶主人，適合承接客戶優先級與正式窗口。",
      vectors: { clarity: 82, context: 74, speed: 66, risk: 72, data: 68, warmth: 56 }
    },
    {
      id: "mandy-chen",
      name: "Mandy Chen",
      role: "處副總經理",
      department: "業務七處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務七處主管，GAP 來訪 prep 協調主責，適合把正式客戶節點與內部準備接起來。",
      vectors: { clarity: 82, context: 76, speed: 68, risk: 72, data: 68, warmth: 58 }
    },
    {
      id: "ivy-liao",
      name: "Ivy Liao",
      role: "A部 lead + 專案整合",
      department: "業務一處 / A部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處 A部 lead，適合處理 BR/UA/ATH/GS/GO/IPSS 與專案整合。",
      vectors: { clarity: 78, context: 76, speed: 68, risk: 70, data: 68, warmth: 58 }
    },
    {
      id: "erica-hsu",
      name: "Erica Hsu",
      role: "B部 head",
      department: "業務一處 / B部 GAP GO Knits",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處 B部 head，負責 GAP/GO Knits，適合處理客戶帳戶與開發量產整合。",
      vectors: { clarity: 78, context: 70, speed: 68, risk: 74, data: 68, warmth: 54 }
    },
    {
      id: "ellen-chang",
      name: "Ellen Chang",
      role: "採購課 head",
      department: "業務一處 / 採購課",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務一處採購課 head，適合主料、副料與跨品牌採購整合。",
      vectors: { clarity: 76, context: 66, speed: 68, risk: 80, data: 74, warmth: 52 }
    },
    {
      id: "tania-liu",
      name: "Tania Liu",
      role: "業務統籌",
      department: "業務二處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處統籌，處理 Sanmar、DKS、Calia、VRST 等業務二處主軸。",
      vectors: { clarity: 78, context: 72, speed: 68, risk: 72, data: 68, warmth: 56 }
    },
    {
      id: "jessica-wang",
      name: "Jessica Wang",
      role: "Development lead",
      department: "業務二處 / A部 DKS-Calia-VRST / Sanmar",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處 A部 Development lead，適合處理 DKS-Calia/VRST 與 Sanmar 開發線。",
      vectors: { clarity: 74, context: 72, speed: 70, risk: 68, data: 66, warmth: 60 }
    },
    {
      id: "vince-hsu",
      name: "Vince Hsu",
      role: "B部負責人",
      department: "業務二處 / B部 DKS-DSG PG AP Golf",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務二處 B部負責人，適合處理 DSG/PG/AP/Golf 帳戶與跨線協調。",
      vectors: { clarity: 78, context: 68, speed: 68, risk: 74, data: 68, warmth: 54 }
    },
    {
      id: "cynthia-fu",
      name: "Cynthia Fu",
      role: "處長",
      department: "業務三處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務三處主管，負責 NET、HLF、A&F、WMT、KOH 等多品牌全處統籌。",
      vectors: { clarity: 80, context: 72, speed: 66, risk: 76, data: 70, warmth: 54 }
    },
    {
      id: "sasha-lai",
      name: "Sasha Lai",
      role: "處副總經理",
      department: "業務五處",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處主管，負責 TGT/GAP_TSD 全處統籌，適合放入 Target 相關任務。",
      vectors: { clarity: 80, context: 72, speed: 68, risk: 74, data: 70, warmth: 56 }
    },
    {
      id: "ruo-chen",
      name: "Ruo Chen",
      role: "Development lead",
      department: "業務五處 / A部 TGT Performance",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處 A部 TGT Performance Development lead；與 3D 的 ROU 不同人。",
      vectors: { clarity: 74, context: 70, speed: 68, risk: 72, data: 68, warmth: 58 }
    },
    {
      id: "maggie-tsai",
      name: "Maggie Tsai",
      role: "Production",
      department: "業務五處 / C部 TGT Adult Sleepwear",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務五處 C部 Production 成員，適合放入 TGT Adult Sleepwear 與新客戶生產線情境。",
      vectors: { clarity: 66, context: 70, speed: 66, risk: 64, data: 62, warmth: 66 }
    },
    {
      id: "emily-chak",
      name: "Emily Chak",
      role: "執行長室聯絡 + VMI/RnR/CA 專案",
      department: "業務行銷群 / 業務七處（兼）",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "橫跨執行長室聯絡與業務七處專案，適合當高層訊號與專案執行之間的轉接點。",
      vectors: { clarity: 78, context: 80, speed: 66, risk: 70, data: 68, warmth: 60 }
    },
    {
      id: "melody-lin",
      name: "Melody Lin",
      role: "B部 head + 專案管理",
      department: "業務七處 / B部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務七處 B部 head，兼專案管理與大貨整合，適合 SWIM/FLEECE/FR 與 Beyond Yoga 任務。",
      vectors: { clarity: 80, context: 74, speed: 68, risk: 74, data: 70, warmth: 56 }
    },
    {
      id: "maggie-chen",
      name: "Maggie Chen",
      role: "Development",
      department: "業務七處 / A部 IPS",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "業務七處 A部 Development 成員，適合 IPS Studiosmooth/Sleektech 開發情境。",
      vectors: { clarity: 66, context: 70, speed: 66, risk: 64, data: 62, warmth: 66 }
    },
    {
      id: "yulia-huang",
      name: "Yulia Huang",
      role: "副理",
      department: "行銷發展處 / 材質研發部",
      orgUnit: "sales-marketing",
      birthday: "待補",
      style: "材質研發二課與區域型供應鏈瓜地馬拉兼任角色，適合材質、副料與區域供應鏈情境。",
      vectors: { clarity: 76, context: 72, speed: 64, risk: 78, data: 76, warmth: 56 }
    },
    {
      id: "brian-lin",
      name: "Brian Lin",
      role: "經理",
      department: "工務處 / 工務管理課",
      orgUnit: "tech-rd",
      birthday: "待補",
      style: "工務管理課經理，AI 種子計畫主推者，適合把 AI 轉型變成可執行制度。",
      vectors: { clarity: 80, context: 74, speed: 72, risk: 72, data: 78, warmth: 56 }
    },
    {
      id: "puli-yu",
      name: "Puli Yu",
      role: "轉投資企業",
      department: "轉投資企業",
      orgUnit: "investment",
      birthday: "待補",
      style: "轉投資企業角色，先作為外部事業連動卡，詳細資料待補。",
      vectors: { clarity: 60, context: 64, speed: 54, risk: 64, data: 58, warmth: 58 }
    },
    {
      id: "hongren-huang",
      name: "Hongren Huang",
      role: "轉投資企業",
      department: "轉投資企業",
      orgUnit: "investment",
      birthday: "待補",
      style: "轉投資企業角色，先作為外部事業連動卡，詳細資料待補。",
      vectors: { clarity: 60, context: 64, speed: 54, risk: 64, data: 58, warmth: 58 }
    },
    {
      id: "huihui",
      name: "Huihui",
      role: "專員",
      department: "3D研發中心 / 數位服飾 / 平湖",
      orgUnit: "tech-rd",
      birthday: "待補",
      numerology: "?",
      element: "土",
      zodiac: "待補",
      archetype: "待觀察",
      animal: "待補",
      star: "待補",
      style: "目前觀察資料極少，先以保留判斷和接手風險標記為主。",
      distilled: { confidence: "低", turns: 1, traits: ["資料稀薄", "2D 接手風險", "需直接觀察"] },
      vectors: { clarity: 58, context: 52, speed: 50, risk: 70, data: 54, warmth: 50 }
    }
  ],
  scenarios: [
    {
      id: "delay",
      name: "專案 delay",
      prompt: "交付日期逼近，但關鍵資料還沒到位，需要兩人快速對齊下一步。",
      weights: { clarity: 1.2, speed: 1.1, risk: 1.15, context: .8, warmth: .8, data: 1 }
    },
    {
      id: "vague",
      name: "需求不清楚",
      prompt: "需求描述太抽象，大家以為理解了，但產出方向可能不同。",
      weights: { clarity: 1.25, context: 1.25, risk: 1, speed: .8, warmth: 1, data: .9 }
    },
    {
      id: "demo",
      name: "高層臨時要 demo",
      prompt: "明天要展示，目前只夠做一個可看的版本，必須取捨。",
      weights: { clarity: 1.15, speed: 1.25, risk: 1.1, context: .7, warmth: .8, data: .8 }
    },
    {
      id: "handoff",
      name: "DPC 與數發交接",
      prompt: "需求、資料與系統限制需要在 DPC 與數發之間翻譯清楚。",
      weights: { clarity: 1.15, context: 1.2, data: 1.15, risk: 1, speed: .85, warmth: 1 }
    },
    {
      id: "conflict",
      name: "會議有分歧",
      prompt: "兩邊都覺得自己有道理，但會議正在失焦，需要重新建立共同問題。",
      weights: { warmth: 1.25, context: 1.1, clarity: 1.1, risk: 1.1, speed: .7, data: .9 }
    },
    {
      id: "innovation",
      name: "新想法探索",
      prompt: "要評估一個新 AI 應用是否值得做 prototype。",
      weights: { context: 1.15, speed: 1, data: 1.05, warmth: 1.1, clarity: .95, risk: .85 }
    }
  ],
  orgMissions: [
    {
      id: "fabric-trim-delay",
      name: "Fabric / Trim Lead Time Slip",
      prompt: "主布或副料交期延遲，PP sample、排產和出貨窗口全部被壓縮。玩家必須在五回合內建立替代料、客戶 approval 和產區排程的共同節奏。",
      goal: "鎖定替代料路線、approval owner、產區排程重算與客戶溝通口徑。",
      pressure: { trust: 36, clarity: 30, momentum: 34, friction: 48 },
      weights: { data: 1.25, risk: 1.25, clarity: 1.15, speed: 1.05, context: 1, warmth: .8 }
    },
    {
      id: "pp-sample-loop",
      name: "PP Sample Approval Loop",
      prompt: "PP sample 被退回多輪，fit、construction、material handfeel 和客戶 comment 版本混在一起，bulk production 不能再等。",
      goal: "把退樣原因拆成 fit / construction / material / customer sign-off，決定下一版樣衣的唯一責任人。",
      pressure: { trust: 38, clarity: 27, momentum: 32, friction: 50 },
      weights: { clarity: 1.35, context: 1.15, risk: 1.2, data: 1.15, speed: .9, warmth: .85 }
    },
    {
      id: "spec-version-drift",
      name: "Spec Version Drift",
      prompt: "業務、技術、工廠各自拿到不同版本 spec，QC 判定和現場做法不一致，rework 正在累積。",
      goal: "建立 single source of truth、版本凍結點、變更通知與工廠 access 規則。",
      pressure: { trust: 34, clarity: 24, momentum: 30, friction: 56 },
      weights: { clarity: 1.4, data: 1.35, risk: 1.2, context: 1.1, speed: .8, warmth: .75 }
    },
    {
      id: "qc-rework-spike",
      name: "QC Rework Spike",
      prompt: "inline inspection 發現縫製、裁片、印繡或尺寸問題，返工量上升，on-time delivery 開始危險。",
      goal: "找到 defect root cause、建立 containment、重排檢驗節點並回報客戶風險。",
      pressure: { trust: 33, clarity: 31, momentum: 32, friction: 58 },
      weights: { risk: 1.4, data: 1.25, clarity: 1.15, speed: 1.1, context: .9, warmth: .75 }
    },
    {
      id: "capacity-wip-bottleneck",
      name: "Capacity / WIP Bottleneck",
      prompt: "某條產線 WIP 暴增，瓶頸卡在 sewing、finishing 或 packing；業務仍在追出貨，現場需要取捨。",
      goal: "用 shared timeline 找瓶頸、重排產能、決定是否拆單或改交期。",
      pressure: { trust: 35, clarity: 33, momentum: 28, friction: 52 },
      weights: { speed: 1.25, data: 1.2, risk: 1.2, clarity: 1.1, context: 1, warmth: .8 }
    },
    {
      id: "digital-sample-adoption",
      name: "Digital Sample Adoption",
      prompt: "品牌想縮短 sample loop，但設計、業務、3D、產區對 digital sample 的信任程度不同，必須定義哪些款能用數位樣核准。",
      goal: "建立 digital sample 適用條件、驗收標準、例外處理和客戶教育路徑。",
      pressure: { trust: 40, clarity: 32, momentum: 38, friction: 42 },
      weights: { context: 1.25, clarity: 1.2, data: 1.15, risk: 1.05, speed: 1, warmth: 1 }
    },
    {
      id: "shipment-booking-crunch",
      name: "Shipment Booking Crunch",
      prompt: "Final inspection、packing、booking 和文件節點互相擠壓，船期或空運成本風險升高。",
      goal: "把 inspection pass、packing readiness、booking cut-off 和客戶承諾放進同一張決策表。",
      pressure: { trust: 37, clarity: 32, momentum: 36, friction: 49 },
      weights: { speed: 1.3, risk: 1.2, data: 1.15, clarity: 1.1, context: .9, warmth: .75 }
    },
    {
      id: "costing-margin-squeeze",
      name: "Costing / Margin Squeeze",
      prompt: "客戶 target cost 壓低，但 fabric、labor、freight 或 MOQ 條件不配合；團隊要在報價、設計調整與供應替代間決策。",
      goal: "拆出 cost driver、替代方案、客戶可接受 trade-off 與 margin guardrail。",
      pressure: { trust: 39, clarity: 34, momentum: 34, friction: 44 },
      weights: { data: 1.3, clarity: 1.2, risk: 1.2, context: 1, speed: .9, warmth: .8 }
    },
    {
      id: "sustainability-traceability",
      name: "Traceability Request",
      prompt: "品牌要求供應鏈透明度、材料來源或永續文件，但資料散在採購、工廠、品管和客戶文件裡。",
      goal: "定義資料責任、文件證據鏈、供應商回覆 SLA 與客戶揭露格式。",
      pressure: { trust: 38, clarity: 29, momentum: 31, friction: 46 },
      weights: { data: 1.4, risk: 1.2, context: 1.15, clarity: 1.15, speed: .8, warmth: .85 }
    },
    {
      id: "ai-plm-visibility",
      name: "PLM / AI Visibility Pilot",
      prompt: "公司想用 PLM、portal 或 AI dashboard 改善 lead time visibility，但如果只做工具，不改資料 owner 和例外流程，pilot 會空轉。",
      goal: "定義 pilot scope、資料 owner、例外訊號、成功指標與上線後維運責任。",
      pressure: { trust: 42, clarity: 31, momentum: 40, friction: 38 },
      weights: { clarity: 1.25, data: 1.25, context: 1.2, speed: 1, risk: 1, warmth: .9 }
    }
  ],
  actionTypes: [
    {
      id: "frame",
      name: "Freeze Spec",
      icon: "◇",
      copy: "凍結目前版次、變更點和客戶 approval 條件。",
      vector: "clarity",
      boosts: { clarity: 16, trust: 3, momentum: 4, friction: -3 }
    },
    {
      id: "bridge",
      name: "Handoff Relay",
      icon: "↔",
      copy: "把上一棒輸入翻成下一棒可執行輸出。",
      vector: "context",
      boosts: { trust: 9, clarity: 9, momentum: 3, friction: -8 }
    },
    {
      id: "prototype",
      name: "Make Sample",
      icon: "▣",
      copy: "做一個可驗證樣本或數位樣，縮短抽象討論。",
      vector: "speed",
      boosts: { momentum: 17, clarity: 5, trust: 2, friction: -1 }
    },
    {
      id: "gate",
      name: "Quality Gate",
      icon: "◆",
      copy: "設 inspection、defect、rework 和放行標準。",
      vector: "risk",
      boosts: { clarity: 10, trust: 4, momentum: 2, friction: -10 }
    },
    {
      id: "evidence",
      name: "Evidence Chain",
      icon: "◎",
      copy: "補齊 spec、sample、照片、測試與供應商回覆證據。",
      vector: "data",
      boosts: { clarity: 8, trust: 8, momentum: 5, friction: -5 }
    },
    {
      id: "align",
      name: "Customer Sync",
      icon: "✦",
      copy: "對齊客戶口徑、風險揭露和可接受 trade-off。",
      vector: "warmth",
      boosts: { trust: 15, clarity: 3, momentum: 1, friction: -12 }
    }
  ],
  strategies: [
    {
      id: "bottom-line",
      name: "結論先行",
      text: "先講要做什麼，再補三個理由。",
      boosts: { clarity: 12, speed: 8, trust: 2, friction: -3 },
      fits: ["delay", "demo"]
    },
    {
      id: "context-brief",
      name: "一頁脈絡 brief",
      text: "用一頁說明背景、限制、目標和待決策點。",
      boosts: { clarity: 8, context: 12, trust: 6, friction: -5 },
      fits: ["vague", "handoff", "innovation"]
    },
    {
      id: "owner-risk",
      name: "拆 owner / deadline / risk",
      text: "把模糊討論拆成負責人、期限和風險。",
      boosts: { clarity: 14, trust: 4, momentum: 8, friction: -2 },
      fits: ["delay", "handoff", "demo"]
    },
    {
      id: "data-proof",
      name: "用數據說服",
      text: "先拿證據和樣本，再要求決策。",
      boosts: { clarity: 8, trust: 8, momentum: 4, friction: -3 },
      fits: ["handoff", "innovation"]
    },
    {
      id: "private-align",
      name: "先私下對齊",
      text: "先一對一校準，再進大會議。",
      boosts: { trust: 12, clarity: 4, momentum: 2, friction: -10 },
      fits: ["conflict", "vague"]
    },
    {
      id: "prototype",
      name: "轉成 prototype",
      text: "用可看的小版本取代長時間抽象辯論。",
      boosts: { momentum: 14, clarity: 7, trust: 3, friction: -1 },
      fits: ["innovation", "demo"]
    },
    {
      id: "options",
      name: "把問題變選項題",
      text: "提供 A/B/C 選項和各自代價，讓對方比較好決定。",
      boosts: { clarity: 12, momentum: 8, trust: 5, friction: -4 },
      fits: ["vague", "conflict", "delay"]
    },
    {
      id: "uncertainty",
      name: "先承認不確定",
      text: "先說哪些已知、哪些未知，再決定要補什麼資料。",
      boosts: { trust: 10, clarity: 7, momentum: 2, friction: -6 },
      fits: ["vague", "innovation", "conflict"]
    }
  ],
  elementRelations: {
    "木-火": "相生：願景能推動速度，適合開新局。",
    "火-土": "相生：推動力能落成流程，但要防止過度催促。",
    "土-金": "相生：現實感能長出標準，適合定規格。",
    "金-水": "相生：標準與資訊流能形成判斷，適合做系統化分析。",
    "水-木": "相生：洞察滋養新方向，適合探索。",
    "木-土": "相剋：擴張遇到現實限制，要先講取捨。",
    "土-水": "相剋：穩定與流動拉扯，要用明確邊界保護彈性。",
    "水-火": "相剋：靈感與速度易互相消耗，需要節奏管理。",
    "火-金": "相剋：推動力碰到標準，摩擦高但能打磨決策。",
    "金-木": "相剋：標準會修剪願景，適合做策略取捨。"
  },
  distillations: {
    karen: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "架構型整合者，前線偵測器不夠靈敏。",
      trigger: "需要整合多地資源、協調複雜分工時會啟動。",
      limiter: "被要求直接說出意見時會猶豫，需要明確授權發聲。",
      assignment: "跨地 coordination、人員分工架構設計；品質 gate 需要外部結構支撐。",
      leverage: "架構設計能力與人員配置邏輯。",
      risk: "Elly 不在場時品質標準容易滑動；需要強硬介入時可能形成真空。",
      aiFit: 3
    },
    alan: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "判斷力在，但等待模式預設開啟。",
      trigger: "把「甲方需求定義者」角色講清楚，並授權他主動要求資源。",
      limiter: "交接邊界模糊會加重等待傾向。",
      assignment: "產品規格決策、業務判斷介入、與 Karen 組的需求 interface。",
      leverage: "看得出什麼值得做，商業判斷力可用。",
      risk: "若只被當執行者，會用執行力完成任務但不主動 claim 資源。",
      aiFit: 3
    },
    andy: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "全端獨立研究者，時間節奏需要外部錨點。",
      trigger: "明確 deadline、展會或里程碑壓力，加上研究自主空間。",
      limiter: "沒有外部節點時，自我驅動節奏容易漂移。",
      assignment: "AI 轉型技術研究、前沿工具評估、VR/AR 研發。",
      leverage: "技術深度、自主評估工具、後設反思能力。",
      risk: "完美主義會把標準拉高，形成拖延。",
      aiFit: 5
    },
    yoko: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "組織可靠度的壓艙石，承壓能力被低估。",
      trigger: "給明確授權和足夠資訊，她會自主把事情做好。",
      limiter: "需要強硬介入時偏白臉；目前吸收 Debbie 缺口，負載偏高。",
      assignment: "AI 種子首選、英文對外溝通培養、Debbie 回來後分工重設關鍵點。",
      leverage: "穩定郵件品質、英文能力、主動承接缺口。",
      risk: "超載和強硬度不足。",
      aiFit: 4
    },
    debbie: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "Profile 建立中，英文 presentation 候選之一。",
      trigger: "產假回來是自然重分工節點。",
      limiter: "實際工作觀察資料有限。",
      assignment: "提前設計回歸後定位，不要直接插回舊位置。",
      leverage: "presentation 培養潛力。",
      risk: "資料不足，回歸定位若未設計會延續舊混亂。",
      aiFit: 2
    },
    adia: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "執行力有，主體性需要被點燃。",
      trigger: "給帶邊界的 AI 專案獨立主導，可能啟動主動性。",
      limiter: "開放式任務容易卡住，需要具體方向。",
      assignment: "視覺製作執行、特定專案主導。",
      leverage: "IG 視覺輸出能力與穩定執行。",
      risk: "等指令模式穩定，可能不是短期狀態。",
      aiFit: 2
    },
    jean: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "內容製作者，已在自主導入 AI 工具。",
      trigger: "給品牌視覺和 3D 建模任務，搭配 AI 輔助工作流。",
      limiter: "業務流程理解仍在建立；不要把 VFX/Unreal 工作誤歸給她。",
      assignment: "品牌視覺內容產出、3D 建模執行、AI 輔助工作流建立。",
      leverage: "影片、IG、建模與 AI 半操作模式的自主導入。",
      risk: "技術路線邊界需要保護。",
      aiFit: 3
    },
    rou: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "細節把關者，表達是弱環。",
      trigger: "用 AI 輔助強化表達，並設計 RC 溝通結構。",
      limiter: "知道答案但說不清楚；對外溝通需配對表達能力強的人。",
      assignment: "3D 品質把關、布料驗證。",
      leverage: "布料驗證與 3D 品質細節能力。",
      risk: "與 RC 的溝通障礙若無結構解法，會卡住流程。",
      aiFit: 2
    },
    sixian: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "穩定低調的儲備能量，尚未被充分使用。",
      trigger: "主動增加工作量，觀察較高負載下的判斷品質。",
      limiter: "曝光度低、review 資料薄。",
      assignment: "UA 支援、布料掃測、GAP 布料。",
      leverage: "不出錯、有餘力，曾主動分享 plug-in。",
      risk: "觀察深度不足，潛力可能被低估。",
      aiFit: 2
    },
    chieh: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "執行力穩定，但投入感有觸發點後退潮。",
      trigger: "先直接問撤退原因，再決定 KPI 或支持策略。",
      limiter: "在理解原因前施壓，可能加速離開。",
      assignment: "量產高通量執行；動機結構需先釐清。",
      leverage: "工作量翻倍仍能撐住，執行力穩定。",
      risk: "從主動改善退回 KPI 施壓，速度過快，疑似有未被理解的觸發點。",
      aiFit: 1
    },
    yota: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "獨立主體型技術人員，被地理因素系統性低估。",
      trigger: "跨地協作需主動設計，直接問出差意願，不代替她決定。",
      limiter: "台北視角曝光不足；出差成本不能用台北標準判斷。",
      assignment: "AI 種子候選、流程優化、高技術作工、嘉義在地工作線統籌。",
      leverage: "TD 溝通、主體想法、AI 學習意願。",
      risk: "地理距離造成低估與資訊不對稱。",
      aiFit: 4
    },
    jan: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "PM 型思考者，邏輯清晰、記憶力強、喜歡直接講。",
      trigger: "在 review 中給直接發言位置，讓她被聽到而不只是被討論。",
      limiter: "英文郵件需修；與 Zizi 摩擦需正式會議記錄保護。",
      assignment: "ATH Project Managing、GAP 協調、PM 培養。",
      leverage: "大局觀、1-2-3 直線溝通、專案協調潛力。",
      risk: "地理曝光不足與跨部門摩擦結構化不足。",
      aiFit: 3
    },
    huihui: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "Profile 資料極稀薄，無法做有意義判斷。",
      trigger: "需要先取得直接觀察或自評資料。",
      limiter: "平湖成員在 review 中幾乎缺席。",
      assignment: "若請假，需確認誰能接手 2D 工作。",
      leverage: "目前不可判斷。",
      risk: "接手設計不清時會形成 2D 工作斷點。",
      aiFit: 0
    },
    rock: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "組織的技術 ground truth，也是最大的單點風險。",
      trigger: "展會、交付等外部截止節點有效；需要制度壓力。",
      limiter: "知識嚴重不輸出，口頭要求無效，需文件化義務。",
      assignment: "技術標準制定；必須配套知識輸出和文件交付。",
      leverage: "驗證標準制定、NunoX 應用測試深度。",
      risk: "知識鎖倉與時間管理失誤影響至少三條工作線。",
      aiFit: 1
    },
    tinley: {
      source: "三場績效評估 + org chart + 工作觀察",
      mode: "成長曲線清晰可見，接手意願強。",
      trigger: "繼續接手重要工作，讓成長速度被看見。",
      limiter: "技術深度仍在建立，需要 RC 知識轉移配合。",
      assignment: "TGT 數位布料接手、VivaTech 支援、AI + 布料工作流整合。",
      leverage: "英文郵件改善明顯，主動填補能力缺口。",
      risk: "若 RC 不輸出知識，成長會被上游卡住。",
      aiFit: 3
    }
  }
};
