const GAME_DATA = {
  members: [
    {
      id: "adia",
      name: "Adia",
      role: "專員",
      department: "DPC",
      birthday: "1991-10-28",
      numerology: 4,
      element: "金",
      zodiac: "天蠍座",
      archetype: "建設者",
      animal: "羊",
      star: "天相星",
      style: "重視穩定與交付，適合用清楚範圍和檢核點對齊。",
      distilled: { confidence: "中", turns: 54, traits: ["短句確認", "現場補位", "快速接話"] },
      vectors: { clarity: 82, context: 62, speed: 54, risk: 76, data: 72, warmth: 58 }
    },
    {
      id: "alan",
      name: "Alan",
      role: "專員",
      department: "數發",
      birthday: "1992-01-31",
      numerology: 8,
      element: "水",
      zodiac: "水瓶座",
      archetype: "成就者",
      animal: "猴",
      star: "天同星",
      style: "偏好有目標、有邊界的討論，能接受新方法但需要看到產出。",
      distilled: { confidence: "高", turns: 178, traits: ["進度核對", "工程交接", "問題回覆"] },
      vectors: { clarity: 76, context: 58, speed: 70, risk: 55, data: 68, warmth: 50 }
    },
    {
      id: "alex",
      name: "Alex",
      role: "CEO",
      department: "管理層",
      birthday: "1984-05-01",
      numerology: 1,
      element: "木",
      zodiac: "金牛座",
      archetype: "領導者",
      animal: "鼠",
      star: "天府星",
      style: "適合用願景、取捨與商業結果對話，避免陷入過細的執行枝節。",
      vectors: { clarity: 88, context: 70, speed: 68, risk: 72, data: 66, warmth: 52 }
    },
    {
      id: "andy",
      name: "Andy",
      role: "專員",
      department: "數發",
      birthday: "1996-11-01",
      numerology: 1,
      element: "火",
      zodiac: "天蠍座",
      archetype: "領導者",
      animal: "鼠",
      star: "七殺星",
      style: "推進感強，適合給明確目標和可立即動手的切入點。",
      vectors: { clarity: 74, context: 48, speed: 82, risk: 50, data: 60, warmth: 48 }
    },
    {
      id: "chieh",
      name: "Chieh",
      role: "專員",
      department: "DPC",
      birthday: "1990-03-24",
      numerology: 1,
      element: "土",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "馬",
      star: "破軍星",
      style: "能快速開局，也容易被模糊需求消耗；最好把問題變成選項。",
      distilled: { confidence: "低", turns: 18, traits: ["進度回報", "先解眼前問題", "實作導向"] },
      vectors: { clarity: 80, context: 45, speed: 84, risk: 46, data: 56, warmth: 44 }
    },
    {
      id: "debbie",
      name: "Debbie",
      role: "專員",
      department: "DPC",
      birthday: "1985-04-01",
      numerology: 1,
      element: "木",
      zodiac: "牡羊座",
      archetype: "領導者",
      animal: "牛",
      star: "廉貞星",
      style: "適合直接講重點和預期成果，節奏拖太長會降低耐心。",
      vectors: { clarity: 78, context: 50, speed: 82, risk: 54, data: 58, warmth: 45 }
    },
    {
      id: "dianne",
      name: "Dianne",
      role: "專員",
      department: "Portal:M",
      birthday: "1993-03-18",
      numerology: 7,
      element: "水",
      zodiac: "雙魚座",
      archetype: "探索者",
      animal: "雞",
      star: "太陰星",
      style: "擅長感受脈絡和受眾反應，適合先對齊語氣再進入任務。",
      vectors: { clarity: 62, context: 84, speed: 52, risk: 64, data: 62, warmth: 78 }
    },
    {
      id: "doris",
      name: "Doris",
      role: "專員",
      department: "DPC",
      birthday: "1995-10-22",
      numerology: 11,
      element: "木",
      zodiac: "天秤座",
      archetype: "啟示者",
      animal: "豬",
      star: "天同星",
      style: "在協調和美感判斷上敏銳，適合用共識框架推進。",
      distilled: { confidence: "高", turns: 53, traits: ["deadline 意識", "流程協調", "友善收斂"] },
      vectors: { clarity: 64, context: 78, speed: 54, risk: 60, data: 58, warmth: 82 }
    },
    {
      id: "edison",
      name: "Edison",
      role: "AI 博士（外包）",
      department: "數發",
      birthday: "1989-11-07",
      numerology: 9,
      element: "土",
      zodiac: "天蠍座",
      archetype: "人道者",
      animal: "蛇",
      star: "天同星",
      style: "適合用問題定義、模型限制和可驗證實驗對齊。",
      distilled: { confidence: "高", turns: 345, traits: ["技術補充", "外部脈絡", "限制說明"] },
      vectors: { clarity: 76, context: 72, speed: 48, risk: 78, data: 90, warmth: 56 }
    },
    {
      id: "elly",
      name: "Elly",
      role: "主管",
      department: "數位產品創造處",
      birthday: "1983-04-27",
      numerology: 7,
      element: "木",
      zodiac: "金牛座",
      archetype: "探索者",
      animal: "豬",
      star: "武曲星",
      style: "偏好結論有立場、脈絡夠完整、能回答 so what 的討論。",
      distilled: { confidence: "高", turns: 779, traits: ["高頻提問", "脈絡整合", "行動收斂"] },
      vectors: { clarity: 86, context: 88, speed: 66, risk: 70, data: 78, warmth: 56 }
    },
    {
      id: "emily",
      name: "Emily",
      role: "專員",
      department: "DPC",
      birthday: "1994-04-29",
      numerology: 11,
      element: "木",
      zodiac: "金牛座",
      archetype: "啟示者",
      animal: "狗",
      star: "廉貞星",
      style: "重視品質與穩定判斷，適合用具體案例和明確標準溝通。",
      distilled: { confidence: "高", turns: 125, traits: ["品牌想像", "視覺語言", "教學轉譯"] },
      vectors: { clarity: 78, context: 66, speed: 52, risk: 74, data: 72, warmth: 62 }
    },
    {
      id: "jan",
      name: "Jan",
      role: "專員",
      department: "DPC",
      birthday: "1996-02-26",
      numerology: 8,
      element: "火",
      zodiac: "雙魚座",
      archetype: "成就者",
      animal: "鼠",
      star: "紫微星",
      style: "能把情緒感知轉成成果導向，適合先說目標再保留彈性。",
      distilled: { confidence: "低", turns: 12, traits: ["進度回報", "確認追問", "客戶回饋"] },
      vectors: { clarity: 72, context: 70, speed: 62, risk: 58, data: 62, warmth: 76 }
    },
    {
      id: "jean",
      name: "Jean",
      role: "專員",
      department: "DPC",
      birthday: "2002-05-21",
      numerology: 3,
      element: "水",
      zodiac: "雙子座",
      archetype: "表達者",
      animal: "馬",
      star: "七殺星",
      style: "反應快、點子多，適合用短迭代和可視化產物聚焦。",
      distilled: { confidence: "低", turns: 12, traits: ["執行回報", "版型比較", "做工調整"] },
      vectors: { clarity: 58, context: 56, speed: 86, risk: 42, data: 54, warmth: 66 }
    },
    {
      id: "karen",
      name: "Karen",
      role: "主管",
      department: "DPC",
      birthday: "1986-04-22",
      numerology: 5,
      element: "火",
      zodiac: "金牛座",
      archetype: "自由者",
      animal: "虎",
      star: "七殺星",
      style: "能快速判斷現場可不可行，適合用決策選項和風險交換溝通。",
      distilled: { confidence: "高", turns: 259, traits: ["現場判斷", "催動進度", "直接追問"] },
      vectors: { clarity: 82, context: 56, speed: 74, risk: 68, data: 62, warmth: 50 }
    },
    {
      id: "rock",
      name: "Rock",
      role: "專員",
      department: "數發",
      birthday: "1990-01-28",
      numerology: 3,
      element: "金",
      zodiac: "水瓶座",
      archetype: "表達者",
      animal: "馬",
      star: "天機星",
      style: "適合討論系統關係與替代方案，溝通時要給空間發散再收斂。",
      distilled: { confidence: "低", turns: 12, traits: ["支援補位", "工具操作", "流程整理"] },
      vectors: { clarity: 64, context: 66, speed: 76, risk: 50, data: 68, warmth: 60 }
    },
    {
      id: "rou",
      name: "ROU",
      role: "專員",
      department: "Portal:M",
      birthday: "1999-04-04",
      numerology: 9,
      element: "火",
      zodiac: "牡羊座",
      archetype: "人道者",
      animal: "兔",
      star: "貪狼星",
      style: "對人和內容氛圍敏銳，適合給舞台、方向和清楚的成功樣貌。",
      distilled: { confidence: "低", turns: 19, traits: ["內容跟催", "語氣回報", "社群節奏"] },
      vectors: { clarity: 66, context: 68, speed: 78, risk: 48, data: 54, warmth: 78 }
    },
    {
      id: "sixian",
      name: "Sixian",
      role: "專員",
      department: "DPC",
      birthday: "1990-05-02",
      numerology: 8,
      element: "金",
      zodiac: "金牛座",
      archetype: "成就者",
      animal: "馬",
      star: "太陰星",
      style: "穩定、務實、重視成果，適合用明確 deliverable 對齊。",
      distilled: { confidence: "低", turns: 15, traits: ["支援排程", "確認召集", "短句回覆"] },
      vectors: { clarity: 84, context: 60, speed: 58, risk: 78, data: 74, warmth: 56 }
    },
    {
      id: "tinley",
      name: "Tinley",
      role: "專員",
      department: "DPC",
      birthday: "1995-10-18",
      numerology: 7,
      element: "木",
      zodiac: "天秤座",
      archetype: "探索者",
      animal: "豬",
      star: "紫微星",
      style: "適合處理探索型議題，先給脈絡和判斷準則會更穩。",
      distilled: { confidence: "中", turns: 42, traits: ["詢問可行性", "風險感知", "彈性配合"] },
      vectors: { clarity: 68, context: 82, speed: 54, risk: 62, data: 66, warmth: 72 }
    },
    {
      id: "vanessa",
      name: "Vanessa",
      role: "主管",
      department: "DPC",
      birthday: "1984-12-25",
      numerology: 5,
      element: "木",
      zodiac: "摩羯座",
      archetype: "自由者",
      animal: "鼠",
      star: "巨門星",
      style: "擅長把自由度和現實限制拉在一起，適合討論優先級與資源取捨。",
      distilled: { confidence: "高", turns: 87, traits: ["脈絡說明", "目的重述", "跨方協調"] },
      vectors: { clarity: 84, context: 68, speed: 62, risk: 82, data: 70, warmth: 54 }
    },
    {
      id: "yoko",
      name: "Yoko",
      role: "專員",
      department: "DPC",
      birthday: "1989-07-30",
      numerology: 1,
      element: "金",
      zodiac: "獅子座",
      archetype: "領導者",
      animal: "蛇",
      star: "巨門星",
      style: "適合用明確主張和成果舞台溝通，避免只給零碎任務。",
      distilled: { confidence: "中", turns: 71, traits: ["款式進度", "資源需求", "變更回報"] },
      vectors: { clarity: 76, context: 54, speed: 76, risk: 58, data: 62, warmth: 62 }
    },
    {
      id: "yota",
      name: "Yota",
      role: "專員",
      department: "數發",
      birthday: "1999-04-02",
      numerology: 7,
      element: "土",
      zodiac: "牡羊座",
      archetype: "探索者",
      animal: "兔",
      star: "天府星",
      style: "適合做探索與落地之間的橋接，需要清楚問題和可試驗範圍。",
      distilled: { confidence: "中", turns: 38, traits: ["進度更新", "急件處理", "執行排程"] },
      vectors: { clarity: 72, context: 72, speed: 72, risk: 58, data: 72, warmth: 58 }
    }
  ],
  scenarios: [
    {
      id: "delay",
      name: "專案 delay",
      prompt: "交付日期逼近，但關鍵資料還沒到位，需要兩人快速對齊下一步。",
      weights: { clarity: 1.2, speed: 1.1, risk: 1.15, context: .8, warmth: .8, data: 1 }
    },
    {
      id: "vague",
      name: "需求不清楚",
      prompt: "需求描述太抽象，大家以為理解了，但產出方向可能不同。",
      weights: { clarity: 1.25, context: 1.25, risk: 1, speed: .8, warmth: 1, data: .9 }
    },
    {
      id: "demo",
      name: "高層臨時要 demo",
      prompt: "明天要展示，目前只夠做一個可看的版本，必須取捨。",
      weights: { clarity: 1.15, speed: 1.25, risk: 1.1, context: .7, warmth: .8, data: .8 }
    },
    {
      id: "handoff",
      name: "DPC 與數發交接",
      prompt: "需求、資料與系統限制需要在 DPC 與數發之間翻譯清楚。",
      weights: { clarity: 1.15, context: 1.2, data: 1.15, risk: 1, speed: .85, warmth: 1 }
    },
    {
      id: "conflict",
      name: "會議有分歧",
      prompt: "兩邊都覺得自己有道理，但會議正在失焦，需要重新建立共同問題。",
      weights: { warmth: 1.25, context: 1.1, clarity: 1.1, risk: 1.1, speed: .7, data: .9 }
    },
    {
      id: "innovation",
      name: "新想法探索",
      prompt: "要評估一個新 AI 應用是否值得做 prototype。",
      weights: { context: 1.15, speed: 1, data: 1.05, warmth: 1.1, clarity: .95, risk: .85 }
    }
  ],
  strategies: [
    {
      id: "bottom-line",
      name: "結論先行",
      text: "先講要做什麼，再補三個理由。",
      boosts: { clarity: 12, speed: 8, trust: 2, friction: -3 },
      fits: ["delay", "demo"]
    },
    {
      id: "context-brief",
      name: "一頁脈絡 brief",
      text: "用一頁說明背景、限制、目標和待決策點。",
      boosts: { clarity: 8, context: 12, trust: 6, friction: -5 },
      fits: ["vague", "handoff", "innovation"]
    },
    {
      id: "owner-risk",
      name: "拆 owner / deadline / risk",
      text: "把模糊討論拆成負責人、期限和風險。",
      boosts: { clarity: 14, trust: 4, momentum: 8, friction: -2 },
      fits: ["delay", "handoff", "demo"]
    },
    {
      id: "data-proof",
      name: "用數據說服",
      text: "先拿證據和樣本，再要求決策。",
      boosts: { clarity: 8, trust: 8, momentum: 4, friction: -3 },
      fits: ["handoff", "innovation"]
    },
    {
      id: "private-align",
      name: "先私下對齊",
      text: "先一對一校準，再進大會議。",
      boosts: { trust: 12, clarity: 4, momentum: 2, friction: -10 },
      fits: ["conflict", "vague"]
    },
    {
      id: "prototype",
      name: "轉成 prototype",
      text: "用可看的小版本取代長時間抽象辯論。",
      boosts: { momentum: 14, clarity: 7, trust: 3, friction: -1 },
      fits: ["innovation", "demo"]
    },
    {
      id: "options",
      name: "把問題變選項題",
      text: "提供 A/B/C 選項和各自代價，讓對方比較好決定。",
      boosts: { clarity: 12, momentum: 8, trust: 5, friction: -4 },
      fits: ["vague", "conflict", "delay"]
    },
    {
      id: "uncertainty",
      name: "先承認不確定",
      text: "先說哪些已知、哪些未知，再決定要補什麼資料。",
      boosts: { trust: 10, clarity: 7, momentum: 2, friction: -6 },
      fits: ["vague", "innovation", "conflict"]
    }
  ],
  elementRelations: {
    "木-火": "相生：願景能推動速度，適合開新局。",
    "火-土": "相生：推動力能落成流程，但要防止過度催促。",
    "土-金": "相生：現實感能長出標準，適合定規格。",
    "金-水": "相生：標準與資訊流能形成判斷，適合做系統化分析。",
    "水-木": "相生：洞察滋養新方向，適合探索。",
    "木-土": "相剋：擴張遇到現實限制，要先講取捨。",
    "土-水": "相剋：穩定與流動拉扯，要用明確邊界保護彈性。",
    "水-火": "相剋：靈感與速度易互相消耗，需要節奏管理。",
    "火-金": "相剋：推動力碰到標準，摩擦高但能打磨決策。",
    "金-木": "相剋：標準會修剪願景，適合做策略取捨。"
  }
};
